/*
 * This file is generated by jOOQ.
 */
package org.jooq.lapis.tables.records;


import java.time.LocalDate;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.lapis.tables.YMainMetadataStaging;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class YMainMetadataStagingRecord extends UpdatableRecordImpl<YMainMetadataStagingRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>y_main_metadata_staging.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>y_main_metadata_staging.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>y_main_metadata_staging.source</code>.
     */
    public void setSource(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>y_main_metadata_staging.source</code>.
     */
    public String getSource() {
        return (String) get(1);
    }

    /**
     * Setter for <code>y_main_metadata_staging.source_primary_key</code>.
     */
    public void setSourcePrimaryKey(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>y_main_metadata_staging.source_primary_key</code>.
     */
    public String getSourcePrimaryKey() {
        return (String) get(2);
    }

    /**
     * Setter for <code>y_main_metadata_staging.genbank_accession</code>.
     */
    public void setGenbankAccession(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>y_main_metadata_staging.genbank_accession</code>.
     */
    public String getGenbankAccession() {
        return (String) get(3);
    }

    /**
     * Setter for <code>y_main_metadata_staging.sra_accession</code>.
     */
    public void setSraAccession(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>y_main_metadata_staging.sra_accession</code>.
     */
    public String getSraAccession() {
        return (String) get(4);
    }

    /**
     * Setter for <code>y_main_metadata_staging.gisaid_epi_isl</code>.
     */
    public void setGisaidEpiIsl(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>y_main_metadata_staging.gisaid_epi_isl</code>.
     */
    public String getGisaidEpiIsl() {
        return (String) get(5);
    }

    /**
     * Setter for <code>y_main_metadata_staging.strain</code>.
     */
    public void setStrain(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>y_main_metadata_staging.strain</code>.
     */
    public String getStrain() {
        return (String) get(6);
    }

    /**
     * Setter for <code>y_main_metadata_staging.date</code>.
     */
    public void setDate(LocalDate value) {
        set(7, value);
    }

    /**
     * Getter for <code>y_main_metadata_staging.date</code>.
     */
    public LocalDate getDate() {
        return (LocalDate) get(7);
    }

    /**
     * Setter for <code>y_main_metadata_staging.date_submitted</code>.
     */
    public void setDateSubmitted(LocalDate value) {
        set(8, value);
    }

    /**
     * Getter for <code>y_main_metadata_staging.date_submitted</code>.
     */
    public LocalDate getDateSubmitted() {
        return (LocalDate) get(8);
    }

    /**
     * Setter for <code>y_main_metadata_staging.region</code>.
     */
    public void setRegion(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>y_main_metadata_staging.region</code>.
     */
    public String getRegion() {
        return (String) get(9);
    }

    /**
     * Setter for <code>y_main_metadata_staging.country</code>.
     */
    public void setCountry(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>y_main_metadata_staging.country</code>.
     */
    public String getCountry() {
        return (String) get(10);
    }

    /**
     * Setter for <code>y_main_metadata_staging.division</code>.
     */
    public void setDivision(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>y_main_metadata_staging.division</code>.
     */
    public String getDivision() {
        return (String) get(11);
    }

    /**
     * Setter for <code>y_main_metadata_staging.location</code>.
     */
    public void setLocation(String value) {
        set(12, value);
    }

    /**
     * Getter for <code>y_main_metadata_staging.location</code>.
     */
    public String getLocation() {
        return (String) get(12);
    }

    /**
     * Setter for <code>y_main_metadata_staging.region_exposure</code>.
     */
    public void setRegionExposure(String value) {
        set(13, value);
    }

    /**
     * Getter for <code>y_main_metadata_staging.region_exposure</code>.
     */
    public String getRegionExposure() {
        return (String) get(13);
    }

    /**
     * Setter for <code>y_main_metadata_staging.country_exposure</code>.
     */
    public void setCountryExposure(String value) {
        set(14, value);
    }

    /**
     * Getter for <code>y_main_metadata_staging.country_exposure</code>.
     */
    public String getCountryExposure() {
        return (String) get(14);
    }

    /**
     * Setter for <code>y_main_metadata_staging.division_exposure</code>.
     */
    public void setDivisionExposure(String value) {
        set(15, value);
    }

    /**
     * Getter for <code>y_main_metadata_staging.division_exposure</code>.
     */
    public String getDivisionExposure() {
        return (String) get(15);
    }

    /**
     * Setter for <code>y_main_metadata_staging.host</code>.
     */
    public void setHost(String value) {
        set(16, value);
    }

    /**
     * Getter for <code>y_main_metadata_staging.host</code>.
     */
    public String getHost() {
        return (String) get(16);
    }

    /**
     * Setter for <code>y_main_metadata_staging.age</code>.
     */
    public void setAge(Integer value) {
        set(17, value);
    }

    /**
     * Getter for <code>y_main_metadata_staging.age</code>.
     */
    public Integer getAge() {
        return (Integer) get(17);
    }

    /**
     * Setter for <code>y_main_metadata_staging.sex</code>.
     */
    public void setSex(String value) {
        set(18, value);
    }

    /**
     * Getter for <code>y_main_metadata_staging.sex</code>.
     */
    public String getSex() {
        return (String) get(18);
    }

    /**
     * Setter for <code>y_main_metadata_staging.hospitalized</code>.
     */
    public void setHospitalized(Boolean value) {
        set(19, value);
    }

    /**
     * Getter for <code>y_main_metadata_staging.hospitalized</code>.
     */
    public Boolean getHospitalized() {
        return (Boolean) get(19);
    }

    /**
     * Setter for <code>y_main_metadata_staging.died</code>.
     */
    public void setDied(Boolean value) {
        set(20, value);
    }

    /**
     * Getter for <code>y_main_metadata_staging.died</code>.
     */
    public Boolean getDied() {
        return (Boolean) get(20);
    }

    /**
     * Setter for <code>y_main_metadata_staging.fully_vaccinated</code>.
     */
    public void setFullyVaccinated(Boolean value) {
        set(21, value);
    }

    /**
     * Getter for <code>y_main_metadata_staging.fully_vaccinated</code>.
     */
    public Boolean getFullyVaccinated() {
        return (Boolean) get(21);
    }

    /**
     * Setter for <code>y_main_metadata_staging.sampling_strategy</code>.
     */
    public void setSamplingStrategy(String value) {
        set(22, value);
    }

    /**
     * Getter for <code>y_main_metadata_staging.sampling_strategy</code>.
     */
    public String getSamplingStrategy() {
        return (String) get(22);
    }

    /**
     * Setter for <code>y_main_metadata_staging.pango_lineage</code>.
     */
    public void setPangoLineage(String value) {
        set(23, value);
    }

    /**
     * Getter for <code>y_main_metadata_staging.pango_lineage</code>.
     */
    public String getPangoLineage() {
        return (String) get(23);
    }

    /**
     * Setter for <code>y_main_metadata_staging.nextclade_pango_lineage</code>.
     */
    public void setNextcladePangoLineage(String value) {
        set(24, value);
    }

    /**
     * Getter for <code>y_main_metadata_staging.nextclade_pango_lineage</code>.
     */
    public String getNextcladePangoLineage() {
        return (String) get(24);
    }

    /**
     * Setter for <code>y_main_metadata_staging.nextstrain_clade</code>.
     */
    public void setNextstrainClade(String value) {
        set(25, value);
    }

    /**
     * Getter for <code>y_main_metadata_staging.nextstrain_clade</code>.
     */
    public String getNextstrainClade() {
        return (String) get(25);
    }

    /**
     * Setter for <code>y_main_metadata_staging.gisaid_clade</code>.
     */
    public void setGisaidClade(String value) {
        set(26, value);
    }

    /**
     * Getter for <code>y_main_metadata_staging.gisaid_clade</code>.
     */
    public String getGisaidClade() {
        return (String) get(26);
    }

    /**
     * Setter for <code>y_main_metadata_staging.originating_lab</code>.
     */
    public void setOriginatingLab(String value) {
        set(27, value);
    }

    /**
     * Getter for <code>y_main_metadata_staging.originating_lab</code>.
     */
    public String getOriginatingLab() {
        return (String) get(27);
    }

    /**
     * Setter for <code>y_main_metadata_staging.submitting_lab</code>.
     */
    public void setSubmittingLab(String value) {
        set(28, value);
    }

    /**
     * Getter for <code>y_main_metadata_staging.submitting_lab</code>.
     */
    public String getSubmittingLab() {
        return (String) get(28);
    }

    /**
     * Setter for <code>y_main_metadata_staging.authors</code>.
     */
    public void setAuthors(String value) {
        set(29, value);
    }

    /**
     * Getter for <code>y_main_metadata_staging.authors</code>.
     */
    public String getAuthors() {
        return (String) get(29);
    }

    /**
     * Setter for <code>y_main_metadata_staging.nextclade_qc_overall_score</code>.
     */
    public void setNextcladeQcOverallScore(Double value) {
        set(30, value);
    }

    /**
     * Getter for <code>y_main_metadata_staging.nextclade_qc_overall_score</code>.
     */
    public Double getNextcladeQcOverallScore() {
        return (Double) get(30);
    }

    /**
     * Setter for <code>y_main_metadata_staging.nextclade_qc_missing_data_score</code>.
     */
    public void setNextcladeQcMissingDataScore(Double value) {
        set(31, value);
    }

    /**
     * Getter for <code>y_main_metadata_staging.nextclade_qc_missing_data_score</code>.
     */
    public Double getNextcladeQcMissingDataScore() {
        return (Double) get(31);
    }

    /**
     * Setter for <code>y_main_metadata_staging.nextclade_qc_mixed_sites_score</code>.
     */
    public void setNextcladeQcMixedSitesScore(Double value) {
        set(32, value);
    }

    /**
     * Getter for <code>y_main_metadata_staging.nextclade_qc_mixed_sites_score</code>.
     */
    public Double getNextcladeQcMixedSitesScore() {
        return (Double) get(32);
    }

    /**
     * Setter for <code>y_main_metadata_staging.nextclade_qc_private_mutations_score</code>.
     */
    public void setNextcladeQcPrivateMutationsScore(Double value) {
        set(33, value);
    }

    /**
     * Getter for <code>y_main_metadata_staging.nextclade_qc_private_mutations_score</code>.
     */
    public Double getNextcladeQcPrivateMutationsScore() {
        return (Double) get(33);
    }

    /**
     * Setter for <code>y_main_metadata_staging.nextclade_qc_snp_clusters_score</code>.
     */
    public void setNextcladeQcSnpClustersScore(Double value) {
        set(34, value);
    }

    /**
     * Getter for <code>y_main_metadata_staging.nextclade_qc_snp_clusters_score</code>.
     */
    public Double getNextcladeQcSnpClustersScore() {
        return (Double) get(34);
    }

    /**
     * Setter for <code>y_main_metadata_staging.nextclade_qc_frame_shifts_score</code>.
     */
    public void setNextcladeQcFrameShiftsScore(Double value) {
        set(35, value);
    }

    /**
     * Getter for <code>y_main_metadata_staging.nextclade_qc_frame_shifts_score</code>.
     */
    public Double getNextcladeQcFrameShiftsScore() {
        return (Double) get(35);
    }

    /**
     * Setter for <code>y_main_metadata_staging.nextclade_qc_stop_codons_score</code>.
     */
    public void setNextcladeQcStopCodonsScore(Double value) {
        set(36, value);
    }

    /**
     * Getter for <code>y_main_metadata_staging.nextclade_qc_stop_codons_score</code>.
     */
    public Double getNextcladeQcStopCodonsScore() {
        return (Double) get(36);
    }

    /**
     * Setter for <code>y_main_metadata_staging.year</code>.
     */
    public void setYear(Integer value) {
        set(37, value);
    }

    /**
     * Getter for <code>y_main_metadata_staging.year</code>.
     */
    public Integer getYear() {
        return (Integer) get(37);
    }

    /**
     * Setter for <code>y_main_metadata_staging.month</code>.
     */
    public void setMonth(Integer value) {
        set(38, value);
    }

    /**
     * Getter for <code>y_main_metadata_staging.month</code>.
     */
    public Integer getMonth() {
        return (Integer) get(38);
    }

    /**
     * Setter for <code>y_main_metadata_staging.day</code>.
     */
    public void setDay(Integer value) {
        set(39, value);
    }

    /**
     * Getter for <code>y_main_metadata_staging.day</code>.
     */
    public Integer getDay() {
        return (Integer) get(39);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached YMainMetadataStagingRecord
     */
    public YMainMetadataStagingRecord() {
        super(YMainMetadataStaging.Y_MAIN_METADATA_STAGING);
    }

    /**
     * Create a detached, initialised YMainMetadataStagingRecord
     */
    public YMainMetadataStagingRecord(Integer id, String source, String sourcePrimaryKey, String genbankAccession, String sraAccession, String gisaidEpiIsl, String strain, LocalDate date, LocalDate dateSubmitted, String region, String country, String division, String location, String regionExposure, String countryExposure, String divisionExposure, String host, Integer age, String sex, Boolean hospitalized, Boolean died, Boolean fullyVaccinated, String samplingStrategy, String pangoLineage, String nextcladePangoLineage, String nextstrainClade, String gisaidClade, String originatingLab, String submittingLab, String authors, Double nextcladeQcOverallScore, Double nextcladeQcMissingDataScore, Double nextcladeQcMixedSitesScore, Double nextcladeQcPrivateMutationsScore, Double nextcladeQcSnpClustersScore, Double nextcladeQcFrameShiftsScore, Double nextcladeQcStopCodonsScore, Integer year, Integer month, Integer day) {
        super(YMainMetadataStaging.Y_MAIN_METADATA_STAGING);

        setId(id);
        setSource(source);
        setSourcePrimaryKey(sourcePrimaryKey);
        setGenbankAccession(genbankAccession);
        setSraAccession(sraAccession);
        setGisaidEpiIsl(gisaidEpiIsl);
        setStrain(strain);
        setDate(date);
        setDateSubmitted(dateSubmitted);
        setRegion(region);
        setCountry(country);
        setDivision(division);
        setLocation(location);
        setRegionExposure(regionExposure);
        setCountryExposure(countryExposure);
        setDivisionExposure(divisionExposure);
        setHost(host);
        setAge(age);
        setSex(sex);
        setHospitalized(hospitalized);
        setDied(died);
        setFullyVaccinated(fullyVaccinated);
        setSamplingStrategy(samplingStrategy);
        setPangoLineage(pangoLineage);
        setNextcladePangoLineage(nextcladePangoLineage);
        setNextstrainClade(nextstrainClade);
        setGisaidClade(gisaidClade);
        setOriginatingLab(originatingLab);
        setSubmittingLab(submittingLab);
        setAuthors(authors);
        setNextcladeQcOverallScore(nextcladeQcOverallScore);
        setNextcladeQcMissingDataScore(nextcladeQcMissingDataScore);
        setNextcladeQcMixedSitesScore(nextcladeQcMixedSitesScore);
        setNextcladeQcPrivateMutationsScore(nextcladeQcPrivateMutationsScore);
        setNextcladeQcSnpClustersScore(nextcladeQcSnpClustersScore);
        setNextcladeQcFrameShiftsScore(nextcladeQcFrameShiftsScore);
        setNextcladeQcStopCodonsScore(nextcladeQcStopCodonsScore);
        setYear(year);
        setMonth(month);
        setDay(day);
    }
}
