/*
 * This file is generated by jOOQ.
 */
package org.jooq.lapis.tables.records;


import java.time.LocalDate;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.lapis.tables.YNextstrainMpox;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class YNextstrainMpoxRecord extends UpdatableRecordImpl<YNextstrainMpoxRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>y_nextstrain_mpox.metadata_hash</code>.
     */
    public void setMetadataHash(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>y_nextstrain_mpox.metadata_hash</code>.
     */
    public String getMetadataHash() {
        return (String) get(0);
    }

    /**
     * Setter for <code>y_nextstrain_mpox.seq_original_hash</code>.
     */
    public void setSeqOriginalHash(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>y_nextstrain_mpox.seq_original_hash</code>.
     */
    public String getSeqOriginalHash() {
        return (String) get(1);
    }

    /**
     * Setter for <code>y_nextstrain_mpox.seq_aligned_hash</code>.
     */
    public void setSeqAlignedHash(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>y_nextstrain_mpox.seq_aligned_hash</code>.
     */
    public String getSeqAlignedHash() {
        return (String) get(2);
    }

    /**
     * Setter for <code>y_nextstrain_mpox.strain</code>.
     */
    public void setStrain(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>y_nextstrain_mpox.strain</code>.
     */
    public String getStrain() {
        return (String) get(3);
    }

    /**
     * Setter for <code>y_nextstrain_mpox.sra_accession</code>.
     */
    public void setSraAccession(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>y_nextstrain_mpox.sra_accession</code>.
     */
    public String getSraAccession() {
        return (String) get(4);
    }

    /**
     * Setter for <code>y_nextstrain_mpox.date</code>.
     */
    public void setDate(LocalDate value) {
        set(5, value);
    }

    /**
     * Getter for <code>y_nextstrain_mpox.date</code>.
     */
    public LocalDate getDate() {
        return (LocalDate) get(5);
    }

    /**
     * Setter for <code>y_nextstrain_mpox.year</code>.
     */
    public void setYear(Integer value) {
        set(6, value);
    }

    /**
     * Getter for <code>y_nextstrain_mpox.year</code>.
     */
    public Integer getYear() {
        return (Integer) get(6);
    }

    /**
     * Setter for <code>y_nextstrain_mpox.month</code>.
     */
    public void setMonth(Integer value) {
        set(7, value);
    }

    /**
     * Getter for <code>y_nextstrain_mpox.month</code>.
     */
    public Integer getMonth() {
        return (Integer) get(7);
    }

    /**
     * Setter for <code>y_nextstrain_mpox.day</code>.
     */
    public void setDay(Integer value) {
        set(8, value);
    }

    /**
     * Getter for <code>y_nextstrain_mpox.day</code>.
     */
    public Integer getDay() {
        return (Integer) get(8);
    }

    /**
     * Setter for <code>y_nextstrain_mpox.date_original</code>.
     */
    public void setDateOriginal(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>y_nextstrain_mpox.date_original</code>.
     */
    public String getDateOriginal() {
        return (String) get(9);
    }

    /**
     * Setter for <code>y_nextstrain_mpox.region</code>.
     */
    public void setRegion(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>y_nextstrain_mpox.region</code>.
     */
    public String getRegion() {
        return (String) get(10);
    }

    /**
     * Setter for <code>y_nextstrain_mpox.country</code>.
     */
    public void setCountry(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>y_nextstrain_mpox.country</code>.
     */
    public String getCountry() {
        return (String) get(11);
    }

    /**
     * Setter for <code>y_nextstrain_mpox.division</code>.
     */
    public void setDivision(String value) {
        set(12, value);
    }

    /**
     * Getter for <code>y_nextstrain_mpox.division</code>.
     */
    public String getDivision() {
        return (String) get(12);
    }

    /**
     * Setter for <code>y_nextstrain_mpox.host</code>.
     */
    public void setHost(String value) {
        set(13, value);
    }

    /**
     * Getter for <code>y_nextstrain_mpox.host</code>.
     */
    public String getHost() {
        return (String) get(13);
    }

    /**
     * Setter for <code>y_nextstrain_mpox.clade</code>.
     */
    public void setClade(String value) {
        set(14, value);
    }

    /**
     * Getter for <code>y_nextstrain_mpox.clade</code>.
     */
    public String getClade() {
        return (String) get(14);
    }

    /**
     * Setter for <code>y_nextstrain_mpox.seq_original_compressed</code>.
     */
    public void setSeqOriginalCompressed(byte[] value) {
        set(15, value);
    }

    /**
     * Getter for <code>y_nextstrain_mpox.seq_original_compressed</code>.
     */
    public byte[] getSeqOriginalCompressed() {
        return (byte[]) get(15);
    }

    /**
     * Setter for <code>y_nextstrain_mpox.seq_aligned_compressed</code>.
     */
    public void setSeqAlignedCompressed(byte[] value) {
        set(16, value);
    }

    /**
     * Getter for <code>y_nextstrain_mpox.seq_aligned_compressed</code>.
     */
    public byte[] getSeqAlignedCompressed() {
        return (byte[]) get(16);
    }

    /**
     * Setter for <code>y_nextstrain_mpox.aa_seqs_compressed</code>.
     */
    public void setAaSeqsCompressed(byte[] value) {
        set(17, value);
    }

    /**
     * Getter for <code>y_nextstrain_mpox.aa_seqs_compressed</code>.
     */
    public byte[] getAaSeqsCompressed() {
        return (byte[]) get(17);
    }

    /**
     * Setter for <code>y_nextstrain_mpox.aa_mutations</code>.
     */
    public void setAaMutations(String value) {
        set(18, value);
    }

    /**
     * Getter for <code>y_nextstrain_mpox.aa_mutations</code>.
     */
    public String getAaMutations() {
        return (String) get(18);
    }

    /**
     * Setter for <code>y_nextstrain_mpox.aa_unknowns</code>.
     */
    public void setAaUnknowns(String value) {
        set(19, value);
    }

    /**
     * Getter for <code>y_nextstrain_mpox.aa_unknowns</code>.
     */
    public String getAaUnknowns() {
        return (String) get(19);
    }

    /**
     * Setter for <code>y_nextstrain_mpox.nuc_substitutions</code>.
     */
    public void setNucSubstitutions(String value) {
        set(20, value);
    }

    /**
     * Getter for <code>y_nextstrain_mpox.nuc_substitutions</code>.
     */
    public String getNucSubstitutions() {
        return (String) get(20);
    }

    /**
     * Setter for <code>y_nextstrain_mpox.nuc_deletions</code>.
     */
    public void setNucDeletions(String value) {
        set(21, value);
    }

    /**
     * Getter for <code>y_nextstrain_mpox.nuc_deletions</code>.
     */
    public String getNucDeletions() {
        return (String) get(21);
    }

    /**
     * Setter for <code>y_nextstrain_mpox.nuc_insertions</code>.
     */
    public void setNucInsertions(String value) {
        set(22, value);
    }

    /**
     * Getter for <code>y_nextstrain_mpox.nuc_insertions</code>.
     */
    public String getNucInsertions() {
        return (String) get(22);
    }

    /**
     * Setter for <code>y_nextstrain_mpox.nuc_unknowns</code>.
     */
    public void setNucUnknowns(String value) {
        set(23, value);
    }

    /**
     * Getter for <code>y_nextstrain_mpox.nuc_unknowns</code>.
     */
    public String getNucUnknowns() {
        return (String) get(23);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached YNextstrainMpoxRecord
     */
    public YNextstrainMpoxRecord() {
        super(YNextstrainMpox.Y_NEXTSTRAIN_MPOX);
    }

    /**
     * Create a detached, initialised YNextstrainMpoxRecord
     */
    public YNextstrainMpoxRecord(String metadataHash, String seqOriginalHash, String seqAlignedHash, String strain, String sraAccession, LocalDate date, Integer year, Integer month, Integer day, String dateOriginal, String region, String country, String division, String host, String clade, byte[] seqOriginalCompressed, byte[] seqAlignedCompressed, byte[] aaSeqsCompressed, String aaMutations, String aaUnknowns, String nucSubstitutions, String nucDeletions, String nucInsertions, String nucUnknowns) {
        super(YNextstrainMpox.Y_NEXTSTRAIN_MPOX);

        setMetadataHash(metadataHash);
        setSeqOriginalHash(seqOriginalHash);
        setSeqAlignedHash(seqAlignedHash);
        setStrain(strain);
        setSraAccession(sraAccession);
        setDate(date);
        setYear(year);
        setMonth(month);
        setDay(day);
        setDateOriginal(dateOriginal);
        setRegion(region);
        setCountry(country);
        setDivision(division);
        setHost(host);
        setClade(clade);
        setSeqOriginalCompressed(seqOriginalCompressed);
        setSeqAlignedCompressed(seqAlignedCompressed);
        setAaSeqsCompressed(aaSeqsCompressed);
        setAaMutations(aaMutations);
        setAaUnknowns(aaUnknowns);
        setNucSubstitutions(nucSubstitutions);
        setNucDeletions(nucDeletions);
        setNucInsertions(nucInsertions);
        setNucUnknowns(nucUnknowns);
    }
}
