@startuml
'https://plantuml.com/component-diagram

package "External Databases" {
    database "GISAID/\nOpen" as externalDB
    database "OWID/\nPangoDesignation" as serverDB
}

package LAPIS {
    [In Memory DB]
    [API]
  [Update Pipeline]
}

package "Cov-Spectrum-Server" {
    [Server API]
    database "Server Postgres DB"
}

database "Lapis Postgres DB"

[Server API] -down-> [Website] : additional data
"Server Postgres DB" -left-> [Server API]
serverDB -> "Server Postgres DB" : scheduled job

API -down-> [Website] : sequence data
API <- [In Memory DB]
"Lapis Postgres DB" -down-> API

externalDB -down-> [Update Pipeline] : preprocessing
[Update Pipeline] -up-> "Lapis Postgres DB" : scheduled job
"Lapis Postgres DB" -right-> [In Memory DB] : "at program start /\n new data available"

@enduml