@startuml

actor Enduser as "End-user"
actor maintainer as "Maintainer"

component SILO-LAPIS as "SILO-LAPIS" {
    portout restInterface as "REST Interface"
    portin inputData as "input data"

    file "Configuration File" as config
}


folder InputData as "Sequence data on disk" {
}


Enduser <-up-> restInterface


InputData -d-> inputData


maintainer -r-> config: provides
maintainer -r-> "SILO-LAPIS": triggers update of data


@enduml