version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
  - package-ecosystem: gradle
    directory: server/
    schedule:
      interval: weekly
  - package-ecosystem: gradle
    directory: lapis2/
    schedule:
      interval: weekly
    groups:
      minorAndPatch:
        update-types:
          - "minor"
          - "patch"
  - package-ecosystem: npm
    directory: siloLapisTests/
    schedule:
      interval: weekly
    groups:
      minorAndPatch:
        update-types:
          - "minor"
          - "patch"