version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    commit-message:
      prefix: "chore(github-actions)"
  - package-ecosystem: gradle
    directory: lapis/
    schedule:
      interval: weekly
    groups:
      minorAndPatch:
        update-types:
          - "minor"
          - "patch"
    commit-message:
      prefix: "chore(lapis)"
  - package-ecosystem: npm
    directory: lapis-e2e/
    schedule:
      interval: weekly
    groups:
      minorAndPatch:
        update-types:
          - "minor"
          - "patch"
    commit-message:
      prefix: "chore(lapis-e2e)"
  - package-ecosystem: npm
    directory: lapis-docs/
    schedule:
      interval: weekly
    groups:
      minorAndPatch:
        update-types:
          - "minor"
          - "patch"
    commit-message:
      prefix: "chore(lapis-docs)"
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    groups:
      minorAndPatch:
        update-types:
          - "minor"
          - "patch"
    commit-message:
      prefix: "chore(root)"