version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    commit-message:
      prefix: "chore(github-actions)"
  - package-ecosystem: gradle
    directory: lapis2/
    schedule:
      interval: weekly
    groups:
      minorAndPatch:
        update-types:
          - "minor"
          - "patch"
    commit-message:
      prefix: "chore(lapis2)"
  - package-ecosystem: npm
    directory: siloLapisTests/
    schedule:
      interval: weekly
    groups:
      minorAndPatch:
        update-types:
          - "minor"
          - "patch"
    commit-message:
      prefix: "chore(siloLapisTests)"
  - package-ecosystem: npm
    directory: lapis2-docs/
    schedule:
      interval: weekly
    groups:
      minorAndPatch:
        update-types:
          - "minor"
          - "patch"
    commit-message:
      prefix: "chore(lapis2-docs)"
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    groups:
      minorAndPatch:
        update-types:
          - "minor"
          - "patch"
    commit-message:
      prefix: "chore(root)"