/*
 * This file is generated by jOOQ.
 */
package org.jooq.y.routines;


import org.jooq.impl.AbstractRoutine;
import org.jooq.y.Public;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class YSwitchInStagingTables extends AbstractRoutine<java.lang.Void> {

    private static final long serialVersionUID = 1L;

    /**
     * Create a new routine call instance
     */
    public YSwitchInStagingTables() {
        super("y_switch_in_staging_tables", Public.PUBLIC);
    }
}
