version: "3.9"
services:
  lapis:
    image: ghcr.io/genspectrum/lapis-v2:${LAPIS_TAG}
    ports:
      - "8080:8080"
    command: --silo.url=http://silo:8081 --lapis.databaseConfig.path=databaseConfig.yaml
    volumes:
      - type: bind
        source: ${DATABASE_CONFIG}
        target: /workspace/databaseConfig.yaml
        read_only: true
  silo:
    image: ghcr.io/genspectrum/lapis-silo:${SILO_TAG}
    ports:
      - ":8081"
