package ch.ethz.y.api.entity;

public enum AggregationField {

    DATE,
    DATESUBMITTED,
    REGION,
    COUNTRY,
    DIVISION,
    LOCATION,
    REGIONEXPOSURE,
    COUNTRYEXPOSURE,
    DIVISIONEXPOSURE,
    AGE,
    SEX,
    HOST,
    SAMPLINGSTRATEGY,
    PANGOLINEAGE,
    NEXTSTRAINCLADE,
    GISAIDCLADE,
    SUBMITTINGLAB,
    ORIGINATINGLAB;

}
