package ch.ethz.lapis.api.entity;

public enum AggregationField {

    DATE,
    DATESUBMITTED,
    REGION,
    COUNTRY,
    DIVISION,
    LOCATION,
    REGIONEXPOSURE,
    COUNTRYEXPOSURE,
    DIVISIONEXPOSURE,
    AGE,
    SEX,
    HOSPITALIZED,
    DIED,
    FULLYVACCINATED,
    HOST,
    SAMPLINGSTRATEGY,
    PANGOLINEAGE,
    NEXTSTRAINCLADE,
    GISAIDCLADE,
    SUBMITTINGLAB,
    ORIGINATINGLAB;

}
