services:
  lapis-docs:
    image: ${IMAGE}
    platform: linux/amd64
    ports:
      - "4321:3000"
    volumes:
      - ../lapis-e2e/testData/singleSegmented/testDatabaseConfig.yaml:/config/database_config.yaml
      - ../lapis-e2e/testData/singleSegmented/reference_genomes.json:/config/reference_genomes.json
    environment:
      LAPIS_URL: http://localhost:8090
      BASE_URL: /docs/
