## Build app ##

FROM openjdk:16 AS builder
WORKDIR /build/

COPY . .
RUN chmod +x ./gradlew
RUN ./gradlew clean build -x test


## Run server ##

FROM openjdk:16 AS server
WORKDIR /app

COPY --from=builder /build/build/libs/lapis-1.0-SNAPSHOT.jar /app/lapis.jar

EXPOSE 2345
ENTRYPOINT ["java", "-Xmx7g", "-jar", "/app/lapis.jar", "--config", "/app/lapis-config.yml", "Lapis", "--api"]
