/*
 * This file is generated by jOOQ.
 */
package org.jooq.y.tables.records;


import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.y.tables.YMainSequenceStaging;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class YMainSequenceStagingRecord extends UpdatableRecordImpl<YMainSequenceStagingRecord> implements Record7<Integer, byte[], String, String, String, String, byte[]> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.y_main_sequence_staging.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.y_main_sequence_staging.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.y_main_sequence_staging.seq_aligned_compressed</code>.
     */
    public void setSeqAlignedCompressed(byte[] value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.y_main_sequence_staging.seq_aligned_compressed</code>.
     */
    public byte[] getSeqAlignedCompressed() {
        return (byte[]) get(1);
    }

    /**
     * Setter for <code>public.y_main_sequence_staging.aa_mutations</code>.
     */
    public void setAaMutations(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.y_main_sequence_staging.aa_mutations</code>.
     */
    public String getAaMutations() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.y_main_sequence_staging.nuc_substitutions</code>.
     */
    public void setNucSubstitutions(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.y_main_sequence_staging.nuc_substitutions</code>.
     */
    public String getNucSubstitutions() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.y_main_sequence_staging.nuc_deletions</code>.
     */
    public void setNucDeletions(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.y_main_sequence_staging.nuc_deletions</code>.
     */
    public String getNucDeletions() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.y_main_sequence_staging.nuc_insertions</code>.
     */
    public void setNucInsertions(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.y_main_sequence_staging.nuc_insertions</code>.
     */
    public String getNucInsertions() {
        return (String) get(5);
    }

    /**
     * Setter for <code>public.y_main_sequence_staging.seq_original_compressed</code>.
     */
    public void setSeqOriginalCompressed(byte[] value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.y_main_sequence_staging.seq_original_compressed</code>.
     */
    public byte[] getSeqOriginalCompressed() {
        return (byte[]) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row7<Integer, byte[], String, String, String, String, byte[]> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    @Override
    public Row7<Integer, byte[], String, String, String, String, byte[]> valuesRow() {
        return (Row7) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return YMainSequenceStaging.Y_MAIN_SEQUENCE_STAGING.ID;
    }

    @Override
    public Field<byte[]> field2() {
        return YMainSequenceStaging.Y_MAIN_SEQUENCE_STAGING.SEQ_ALIGNED_COMPRESSED;
    }

    @Override
    public Field<String> field3() {
        return YMainSequenceStaging.Y_MAIN_SEQUENCE_STAGING.AA_MUTATIONS;
    }

    @Override
    public Field<String> field4() {
        return YMainSequenceStaging.Y_MAIN_SEQUENCE_STAGING.NUC_SUBSTITUTIONS;
    }

    @Override
    public Field<String> field5() {
        return YMainSequenceStaging.Y_MAIN_SEQUENCE_STAGING.NUC_DELETIONS;
    }

    @Override
    public Field<String> field6() {
        return YMainSequenceStaging.Y_MAIN_SEQUENCE_STAGING.NUC_INSERTIONS;
    }

    @Override
    public Field<byte[]> field7() {
        return YMainSequenceStaging.Y_MAIN_SEQUENCE_STAGING.SEQ_ORIGINAL_COMPRESSED;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public byte[] component2() {
        return getSeqAlignedCompressed();
    }

    @Override
    public String component3() {
        return getAaMutations();
    }

    @Override
    public String component4() {
        return getNucSubstitutions();
    }

    @Override
    public String component5() {
        return getNucDeletions();
    }

    @Override
    public String component6() {
        return getNucInsertions();
    }

    @Override
    public byte[] component7() {
        return getSeqOriginalCompressed();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public byte[] value2() {
        return getSeqAlignedCompressed();
    }

    @Override
    public String value3() {
        return getAaMutations();
    }

    @Override
    public String value4() {
        return getNucSubstitutions();
    }

    @Override
    public String value5() {
        return getNucDeletions();
    }

    @Override
    public String value6() {
        return getNucInsertions();
    }

    @Override
    public byte[] value7() {
        return getSeqOriginalCompressed();
    }

    @Override
    public YMainSequenceStagingRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public YMainSequenceStagingRecord value2(byte[] value) {
        setSeqAlignedCompressed(value);
        return this;
    }

    @Override
    public YMainSequenceStagingRecord value3(String value) {
        setAaMutations(value);
        return this;
    }

    @Override
    public YMainSequenceStagingRecord value4(String value) {
        setNucSubstitutions(value);
        return this;
    }

    @Override
    public YMainSequenceStagingRecord value5(String value) {
        setNucDeletions(value);
        return this;
    }

    @Override
    public YMainSequenceStagingRecord value6(String value) {
        setNucInsertions(value);
        return this;
    }

    @Override
    public YMainSequenceStagingRecord value7(byte[] value) {
        setSeqOriginalCompressed(value);
        return this;
    }

    @Override
    public YMainSequenceStagingRecord values(Integer value1, byte[] value2, String value3, String value4, String value5, String value6, byte[] value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached YMainSequenceStagingRecord
     */
    public YMainSequenceStagingRecord() {
        super(YMainSequenceStaging.Y_MAIN_SEQUENCE_STAGING);
    }

    /**
     * Create a detached, initialised YMainSequenceStagingRecord
     */
    public YMainSequenceStagingRecord(Integer id, byte[] seqAlignedCompressed, String aaMutations, String nucSubstitutions, String nucDeletions, String nucInsertions, byte[] seqOriginalCompressed) {
        super(YMainSequenceStaging.Y_MAIN_SEQUENCE_STAGING);

        setId(id);
        setSeqAlignedCompressed(seqAlignedCompressed);
        setAaMutations(aaMutations);
        setNucSubstitutions(nucSubstitutions);
        setNucDeletions(nucDeletions);
        setNucInsertions(nucInsertions);
        setSeqOriginalCompressed(seqOriginalCompressed);
    }
}
