version: "3.9"
services:
  lapis-docs:
    image: ${IMAGE}
    ports:
      - "3000:3000"
    volumes:
      - ../siloLapisTests/testData/testDatabaseConfig.yaml:/config/database_config.yaml
    environment:
      LAPIS_URL: localhost:8080
