/*
 * This file is generated by jOOQ.
 */
package org.jooq.lapis;


import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;
import org.jooq.lapis.tables.YMainAaSequence;
import org.jooq.lapis.tables.YMainAaSequenceColumnar;
import org.jooq.lapis.tables.YMainAaSequenceColumnarStaging;
import org.jooq.lapis.tables.YMainAaSequenceStaging;
import org.jooq.lapis.tables.YMainMetadata;
import org.jooq.lapis.tables.YMainMetadataStaging;
import org.jooq.lapis.tables.YMainSequence;
import org.jooq.lapis.tables.YMainSequenceColumnar;
import org.jooq.lapis.tables.YMainSequenceColumnarStaging;
import org.jooq.lapis.tables.YMainSequenceStaging;
import org.jooq.lapis.tables.YNextstrainGenbank;
import org.jooq.lapis.tables.YS3c;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DefaultSchema extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>DEFAULT_SCHEMA</code>
     */
    public static final DefaultSchema DEFAULT_SCHEMA = new DefaultSchema();

    /**
     * The table <code>y_main_aa_sequence</code>.
     */
    public final YMainAaSequence Y_MAIN_AA_SEQUENCE = YMainAaSequence.Y_MAIN_AA_SEQUENCE;

    /**
     * The table <code>y_main_aa_sequence_columnar</code>.
     */
    public final YMainAaSequenceColumnar Y_MAIN_AA_SEQUENCE_COLUMNAR = YMainAaSequenceColumnar.Y_MAIN_AA_SEQUENCE_COLUMNAR;

    /**
     * The table <code>y_main_aa_sequence_columnar_staging</code>.
     */
    public final YMainAaSequenceColumnarStaging Y_MAIN_AA_SEQUENCE_COLUMNAR_STAGING = YMainAaSequenceColumnarStaging.Y_MAIN_AA_SEQUENCE_COLUMNAR_STAGING;

    /**
     * The table <code>y_main_aa_sequence_staging</code>.
     */
    public final YMainAaSequenceStaging Y_MAIN_AA_SEQUENCE_STAGING = YMainAaSequenceStaging.Y_MAIN_AA_SEQUENCE_STAGING;

    /**
     * The table <code>y_main_metadata</code>.
     */
    public final YMainMetadata Y_MAIN_METADATA = YMainMetadata.Y_MAIN_METADATA;

    /**
     * The table <code>y_main_metadata_staging</code>.
     */
    public final YMainMetadataStaging Y_MAIN_METADATA_STAGING = YMainMetadataStaging.Y_MAIN_METADATA_STAGING;

    /**
     * The table <code>y_main_sequence</code>.
     */
    public final YMainSequence Y_MAIN_SEQUENCE = YMainSequence.Y_MAIN_SEQUENCE;

    /**
     * The table <code>y_main_sequence_columnar</code>.
     */
    public final YMainSequenceColumnar Y_MAIN_SEQUENCE_COLUMNAR = YMainSequenceColumnar.Y_MAIN_SEQUENCE_COLUMNAR;

    /**
     * The table <code>y_main_sequence_columnar_staging</code>.
     */
    public final YMainSequenceColumnarStaging Y_MAIN_SEQUENCE_COLUMNAR_STAGING = YMainSequenceColumnarStaging.Y_MAIN_SEQUENCE_COLUMNAR_STAGING;

    /**
     * The table <code>y_main_sequence_staging</code>.
     */
    public final YMainSequenceStaging Y_MAIN_SEQUENCE_STAGING = YMainSequenceStaging.Y_MAIN_SEQUENCE_STAGING;

    /**
     * The table <code>y_nextstrain_genbank</code>.
     */
    public final YNextstrainGenbank Y_NEXTSTRAIN_GENBANK = YNextstrainGenbank.Y_NEXTSTRAIN_GENBANK;

    /**
     * The table <code>y_s3c</code>.
     */
    public final YS3c Y_S3C = YS3c.Y_S3C;

    /**
     * No further instances allowed
     */
    private DefaultSchema() {
        super("", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.<Table<?>>asList(
            YMainAaSequence.Y_MAIN_AA_SEQUENCE,
            YMainAaSequenceColumnar.Y_MAIN_AA_SEQUENCE_COLUMNAR,
            YMainAaSequenceColumnarStaging.Y_MAIN_AA_SEQUENCE_COLUMNAR_STAGING,
            YMainAaSequenceStaging.Y_MAIN_AA_SEQUENCE_STAGING,
            YMainMetadata.Y_MAIN_METADATA,
            YMainMetadataStaging.Y_MAIN_METADATA_STAGING,
            YMainSequence.Y_MAIN_SEQUENCE,
            YMainSequenceColumnar.Y_MAIN_SEQUENCE_COLUMNAR,
            YMainSequenceColumnarStaging.Y_MAIN_SEQUENCE_COLUMNAR_STAGING,
            YMainSequenceStaging.Y_MAIN_SEQUENCE_STAGING,
            YNextstrainGenbank.Y_NEXTSTRAIN_GENBANK,
            YS3c.Y_S3C);
    }
}
