@startuml

node RhyDB {
  package "RhyDB Api" {
    component "Query Engine" as query
    component "Runtime Database" as db
    "Web API" -> query
    query -> db
  }

  package "RhyDB Preprocessing" {
    component "Preprocessing Database"
  }
}

@enduml
