@startuml

cloud {
  file "input files" as input
}
folder "Folder with serialized states" as files {
  file "old state"
  file "new state"
}
component "RhyDB Preprocessing" as rhyDbPreprocessing #lightblue
package "RhyDB-LAPIS runtime" {
  component "RhyDB Api" as rhyDbApi #lightblue
  component LAPIS #lightblue
}
actor User

User -> LAPIS : simplified query
User <- LAPIS : data
LAPIS -> rhyDbApi : RhyDB query
LAPIS <- rhyDbApi : data
rhyDbApi <- files : reads newest serialized state
rhyDbPreprocessing --> files : serializes state
input --> rhyDbPreprocessing : reads externally provided input files

@enduml
