/*
 * This file is generated by jOOQ.
 */
package org.jooq.lapis.routines;


import org.jooq.impl.AbstractRoutine;
import org.jooq.lapis.DefaultSchema;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class YSwitchInStagingTablesWithoutTruncate extends AbstractRoutine<java.lang.Void> {

    private static final long serialVersionUID = 1L;

    /**
     * Create a new routine call instance
     */
    public YSwitchInStagingTablesWithoutTruncate() {
        super("y_switch_in_staging_tables_without_truncate", DefaultSchema.DEFAULT_SCHEMA);
    }
}
