/*
 * This file is generated by jOOQ.
 */
package org.jooq.y.tables;


import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row2;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;
import org.jooq.y.Keys;
import org.jooq.y.Public;
import org.jooq.y.tables.records.YMainSequenceColumnarRecord;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class YMainSequenceColumnar extends TableImpl<YMainSequenceColumnarRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.y_main_sequence_columnar</code>
     */
    public static final YMainSequenceColumnar Y_MAIN_SEQUENCE_COLUMNAR = new YMainSequenceColumnar();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<YMainSequenceColumnarRecord> getRecordType() {
        return YMainSequenceColumnarRecord.class;
    }

    /**
     * The column <code>public.y_main_sequence_columnar.position</code>.
     */
    public final TableField<YMainSequenceColumnarRecord, Integer> POSITION = createField(DSL.name("position"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.y_main_sequence_columnar.data_compressed</code>.
     */
    public final TableField<YMainSequenceColumnarRecord, byte[]> DATA_COMPRESSED = createField(DSL.name("data_compressed"), SQLDataType.BLOB.nullable(false), this, "");

    private YMainSequenceColumnar(Name alias, Table<YMainSequenceColumnarRecord> aliased) {
        this(alias, aliased, null);
    }

    private YMainSequenceColumnar(Name alias, Table<YMainSequenceColumnarRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>public.y_main_sequence_columnar</code> table reference
     */
    public YMainSequenceColumnar(String alias) {
        this(DSL.name(alias), Y_MAIN_SEQUENCE_COLUMNAR);
    }

    /**
     * Create an aliased <code>public.y_main_sequence_columnar</code> table reference
     */
    public YMainSequenceColumnar(Name alias) {
        this(alias, Y_MAIN_SEQUENCE_COLUMNAR);
    }

    /**
     * Create a <code>public.y_main_sequence_columnar</code> table reference
     */
    public YMainSequenceColumnar() {
        this(DSL.name("y_main_sequence_columnar"), null);
    }

    public <O extends Record> YMainSequenceColumnar(Table<O> child, ForeignKey<O, YMainSequenceColumnarRecord> key) {
        super(child, key, Y_MAIN_SEQUENCE_COLUMNAR);
    }

    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    @Override
    public UniqueKey<YMainSequenceColumnarRecord> getPrimaryKey() {
        return Keys.Y_MAIN_SEQUENCE_COLUMNAR_STAGING_PKEY;
    }

    @Override
    public List<UniqueKey<YMainSequenceColumnarRecord>> getKeys() {
        return Arrays.<UniqueKey<YMainSequenceColumnarRecord>>asList(Keys.Y_MAIN_SEQUENCE_COLUMNAR_STAGING_PKEY);
    }

    @Override
    public YMainSequenceColumnar as(String alias) {
        return new YMainSequenceColumnar(DSL.name(alias), this);
    }

    @Override
    public YMainSequenceColumnar as(Name alias) {
        return new YMainSequenceColumnar(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public YMainSequenceColumnar rename(String name) {
        return new YMainSequenceColumnar(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public YMainSequenceColumnar rename(Name name) {
        return new YMainSequenceColumnar(name, null);
    }

    // -------------------------------------------------------------------------
    // Row2 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row2<Integer, byte[]> fieldsRow() {
        return (Row2) super.fieldsRow();
    }
}
