/*
 * This file is generated by jOOQ.
 */
package org.jooq.y.tables;


import java.time.LocalDate;
import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;
import org.jooq.y.Keys;
import org.jooq.y.Public;
import org.jooq.y.tables.records.YNextstrainGenbankRecord;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class YNextstrainGenbank extends TableImpl<YNextstrainGenbankRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.y_nextstrain_genbank</code>
     */
    public static final YNextstrainGenbank Y_NEXTSTRAIN_GENBANK = new YNextstrainGenbank();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<YNextstrainGenbankRecord> getRecordType() {
        return YNextstrainGenbankRecord.class;
    }

    /**
     * The column <code>public.y_nextstrain_genbank.genbank_accession</code>.
     */
    public final TableField<YNextstrainGenbankRecord, String> GENBANK_ACCESSION = createField(DSL.name("genbank_accession"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.y_nextstrain_genbank.sra_accession</code>.
     */
    public final TableField<YNextstrainGenbankRecord, String> SRA_ACCESSION = createField(DSL.name("sra_accession"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.y_nextstrain_genbank.gisaid_epi_isl</code>.
     */
    public final TableField<YNextstrainGenbankRecord, String> GISAID_EPI_ISL = createField(DSL.name("gisaid_epi_isl"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.y_nextstrain_genbank.strain</code>.
     */
    public final TableField<YNextstrainGenbankRecord, String> STRAIN = createField(DSL.name("strain"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>public.y_nextstrain_genbank.date</code>.
     */
    public final TableField<YNextstrainGenbankRecord, LocalDate> DATE = createField(DSL.name("date"), SQLDataType.LOCALDATE, this, "");

    /**
     * The column <code>public.y_nextstrain_genbank.date_original</code>.
     */
    public final TableField<YNextstrainGenbankRecord, String> DATE_ORIGINAL = createField(DSL.name("date_original"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.y_nextstrain_genbank.date_submitted</code>.
     */
    public final TableField<YNextstrainGenbankRecord, LocalDate> DATE_SUBMITTED = createField(DSL.name("date_submitted"), SQLDataType.LOCALDATE, this, "");

    /**
     * The column <code>public.y_nextstrain_genbank.region</code>.
     */
    public final TableField<YNextstrainGenbankRecord, String> REGION = createField(DSL.name("region"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.y_nextstrain_genbank.country</code>.
     */
    public final TableField<YNextstrainGenbankRecord, String> COUNTRY = createField(DSL.name("country"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.y_nextstrain_genbank.division</code>.
     */
    public final TableField<YNextstrainGenbankRecord, String> DIVISION = createField(DSL.name("division"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.y_nextstrain_genbank.location</code>.
     */
    public final TableField<YNextstrainGenbankRecord, String> LOCATION = createField(DSL.name("location"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.y_nextstrain_genbank.region_exposure</code>.
     */
    public final TableField<YNextstrainGenbankRecord, String> REGION_EXPOSURE = createField(DSL.name("region_exposure"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.y_nextstrain_genbank.country_exposure</code>.
     */
    public final TableField<YNextstrainGenbankRecord, String> COUNTRY_EXPOSURE = createField(DSL.name("country_exposure"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.y_nextstrain_genbank.division_exposure</code>.
     */
    public final TableField<YNextstrainGenbankRecord, String> DIVISION_EXPOSURE = createField(DSL.name("division_exposure"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.y_nextstrain_genbank.host</code>.
     */
    public final TableField<YNextstrainGenbankRecord, String> HOST = createField(DSL.name("host"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.y_nextstrain_genbank.age</code>.
     */
    public final TableField<YNextstrainGenbankRecord, Integer> AGE = createField(DSL.name("age"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.y_nextstrain_genbank.sex</code>.
     */
    public final TableField<YNextstrainGenbankRecord, String> SEX = createField(DSL.name("sex"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.y_nextstrain_genbank.sampling_strategy</code>.
     */
    public final TableField<YNextstrainGenbankRecord, String> SAMPLING_STRATEGY = createField(DSL.name("sampling_strategy"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.y_nextstrain_genbank.pango_lineage</code>.
     */
    public final TableField<YNextstrainGenbankRecord, String> PANGO_LINEAGE = createField(DSL.name("pango_lineage"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.y_nextstrain_genbank.nextstrain_clade</code>.
     */
    public final TableField<YNextstrainGenbankRecord, String> NEXTSTRAIN_CLADE = createField(DSL.name("nextstrain_clade"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.y_nextstrain_genbank.gisaid_clade</code>.
     */
    public final TableField<YNextstrainGenbankRecord, String> GISAID_CLADE = createField(DSL.name("gisaid_clade"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.y_nextstrain_genbank.originating_lab</code>.
     */
    public final TableField<YNextstrainGenbankRecord, String> ORIGINATING_LAB = createField(DSL.name("originating_lab"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.y_nextstrain_genbank.submitting_lab</code>.
     */
    public final TableField<YNextstrainGenbankRecord, String> SUBMITTING_LAB = createField(DSL.name("submitting_lab"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.y_nextstrain_genbank.authors</code>.
     */
    public final TableField<YNextstrainGenbankRecord, String> AUTHORS = createField(DSL.name("authors"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.y_nextstrain_genbank.seq_original_compressed</code>.
     */
    public final TableField<YNextstrainGenbankRecord, byte[]> SEQ_ORIGINAL_COMPRESSED = createField(DSL.name("seq_original_compressed"), SQLDataType.BLOB, this, "");

    /**
     * The column <code>public.y_nextstrain_genbank.seq_aligned_compressed</code>.
     */
    public final TableField<YNextstrainGenbankRecord, byte[]> SEQ_ALIGNED_COMPRESSED = createField(DSL.name("seq_aligned_compressed"), SQLDataType.BLOB, this, "");

    /**
     * The column <code>public.y_nextstrain_genbank.aa_mutations</code>.
     */
    public final TableField<YNextstrainGenbankRecord, String> AA_MUTATIONS = createField(DSL.name("aa_mutations"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.y_nextstrain_genbank.nuc_insertions</code>.
     */
    public final TableField<YNextstrainGenbankRecord, String> NUC_INSERTIONS = createField(DSL.name("nuc_insertions"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.y_nextstrain_genbank.nuc_substitutions</code>.
     */
    public final TableField<YNextstrainGenbankRecord, String> NUC_SUBSTITUTIONS = createField(DSL.name("nuc_substitutions"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.y_nextstrain_genbank.nuc_deletions</code>.
     */
    public final TableField<YNextstrainGenbankRecord, String> NUC_DELETIONS = createField(DSL.name("nuc_deletions"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.y_nextstrain_genbank.aa_seqs</code>.
     */
    public final TableField<YNextstrainGenbankRecord, String> AA_SEQS = createField(DSL.name("aa_seqs"), SQLDataType.CLOB, this, "");

    private YNextstrainGenbank(Name alias, Table<YNextstrainGenbankRecord> aliased) {
        this(alias, aliased, null);
    }

    private YNextstrainGenbank(Name alias, Table<YNextstrainGenbankRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>public.y_nextstrain_genbank</code> table reference
     */
    public YNextstrainGenbank(String alias) {
        this(DSL.name(alias), Y_NEXTSTRAIN_GENBANK);
    }

    /**
     * Create an aliased <code>public.y_nextstrain_genbank</code> table reference
     */
    public YNextstrainGenbank(Name alias) {
        this(alias, Y_NEXTSTRAIN_GENBANK);
    }

    /**
     * Create a <code>public.y_nextstrain_genbank</code> table reference
     */
    public YNextstrainGenbank() {
        this(DSL.name("y_nextstrain_genbank"), null);
    }

    public <O extends Record> YNextstrainGenbank(Table<O> child, ForeignKey<O, YNextstrainGenbankRecord> key) {
        super(child, key, Y_NEXTSTRAIN_GENBANK);
    }

    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    @Override
    public UniqueKey<YNextstrainGenbankRecord> getPrimaryKey() {
        return Keys.Y_NEXTSTRAIN_GENBANK_PK;
    }

    @Override
    public List<UniqueKey<YNextstrainGenbankRecord>> getKeys() {
        return Arrays.<UniqueKey<YNextstrainGenbankRecord>>asList(Keys.Y_NEXTSTRAIN_GENBANK_PK);
    }

    @Override
    public YNextstrainGenbank as(String alias) {
        return new YNextstrainGenbank(DSL.name(alias), this);
    }

    @Override
    public YNextstrainGenbank as(Name alias) {
        return new YNextstrainGenbank(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public YNextstrainGenbank rename(String name) {
        return new YNextstrainGenbank(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public YNextstrainGenbank rename(Name name) {
        return new YNextstrainGenbank(name, null);
    }
}
