name: LAPIS v2

on: [push]

env:
  DOCKER_IMAGE_NAME: ghcr.io/genspectrum/lapis-v2

jobs:
  Tests:
    runs-on: ubuntu-latest
    steps:
      -
        uses: actions/checkout@v3
      -
        name: Set up JDK 19
        uses: actions/setup-java@v3
        with:
          java-version: '19'
          distribution: 'adopt'
      -
        name: Execute Tests
        uses: gradle/gradle-build-action@v2
        with:
          arguments: test
          build-root-directory: lapis2
      -
        name: Check Format And Lint
        uses: gradle/gradle-build-action@v2
        with:
          arguments: ktlintCheck
          build-root-directory: lapis2

  dockerImage:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      -
        uses: actions/checkout@v3
      -
        name: Set up JDK 19
        uses: actions/setup-java@v3
        with:
          java-version: '19'
          distribution: 'adopt'
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Docker metadata
        id: dockerMetadata
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.DOCKER_IMAGE_NAME }}
          tags: type=ref,event=branch
      -
        name: Build Docker Image For Branch
        uses: gradle/gradle-build-action@v2
        env:
          USER: ${{ github.actor }}
          TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        with:
          arguments: bootBuildImage --imageName=${{ steps.dockerMetadata.outputs.tags }}
          build-root-directory: lapis2
      -
        name: Push Docker Image For Branch
        run: docker push ${{ steps.dockerMetadata.outputs.tags }}
      -
        name: Build "public" Docker Image
        if: ${{ github.ref == format('refs/heads/{0}', 'public') }}
        uses: gradle/gradle-build-action@v2
        with:
          arguments: bootBuildImage --imageName=${{ env.DOCKER_IMAGE_NAME }}:public
          build-root-directory: lapis2
      -
        name: Push "public" Docker Image
        if: ${{ github.ref == format('refs/heads/{0}', 'public') }}
        run: docker push ${{ env.DOCKER_IMAGE_NAME }}:public