name: LAPIS v2 Docs

on: [push]

env:
  DOCKER_IMAGE_NAME: ghcr.io/genspectrum/lapis-v2-docs

jobs:
  dockerImage:
    name: Build Docker Image
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      -
        uses: actions/checkout@v4
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Docker metadata
        id: dockerMetadata
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.DOCKER_IMAGE_NAME }}
          tags: |
            type=ref,event=branch,enable=${{ github.ref != 'refs/heads/main' }}
            type=raw,value=latest,enable=${{ github.ref == 'refs/heads/main' }}
      -
        name: Build and push image
        uses: docker/build-push-action@v4
        with:
          context: ./lapis2-docs
          push: true
          tags: ${{ steps.dockerMetadata.outputs.tags }}
      -
        name: Start Docker container and check that it responds
        run: |
          docker compose -f lapis2-docs/test-docker-compose.yml up -d --wait
          curl --fail --silent localhost:3000/docs/ | grep "Welcome to LAPIS" \
            || (echo "Did not find expected text in website" && exit 1)
        env:
          IMAGE: ${{ steps.dockerMetadata.outputs.tags }}
