name: LAPIS v2

on: [push]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 19
        uses: actions/setup-java@v3
        with:
          java-version: '19'
          distribution: 'adopt'
      - name: Execute tests
        uses: gradle/gradle-build-action@v2
        with:
          arguments: test
          build-root-directory: lapis2
