name: Docker (swagger)

on:
  push:
    branches:
  schedule:
    - cron: '0 7 */2 * *'

env:
  IMAGE_NAME: ghcr.io/cevo-public/lapis-swagger

jobs:
  docker:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./docs/openapi_spec
    steps:
      - uses: actions/checkout@v2
      - name: Set environment variable "BRANCH"
        run: |
          echo "BRANCH=$(eval 'echo $GITHUB_REF | sed s/refs\\/heads\\/// | sed s/\\//__/ ')" >> $GITHUB_ENV
      - name: Build image
        run: docker build -t new_image .
      - name: Login to Github Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - name: Add tags and push
        run: |
          docker tag new_image ${{ env.IMAGE_NAME }}:br-${{ env.BRANCH }}
          docker push ${{ env.IMAGE_NAME }}:br-${{ env.BRANCH }}
      - name: Add "public" tag and push
        if: env.BRANCH == 'public'
        run: |
          docker tag new_image ${{ env.IMAGE_NAME }}:public
          docker push ${{ env.IMAGE_NAME }}:public
