/*
 * This file is generated by jOOQ.
 */
package org.jooq.lapis.tables;


import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row3;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;
import org.jooq.lapis.DefaultSchema;
import org.jooq.lapis.Keys;
import org.jooq.lapis.tables.records.YMainAaSequenceRecord;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class YMainAaSequence extends TableImpl<YMainAaSequenceRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>y_main_aa_sequence</code>
     */
    public static final YMainAaSequence Y_MAIN_AA_SEQUENCE = new YMainAaSequence();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<YMainAaSequenceRecord> getRecordType() {
        return YMainAaSequenceRecord.class;
    }

    /**
     * The column <code>y_main_aa_sequence.id</code>.
     */
    public final TableField<YMainAaSequenceRecord, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>y_main_aa_sequence.gene</code>.
     */
    public final TableField<YMainAaSequenceRecord, String> GENE = createField(DSL.name("gene"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>y_main_aa_sequence.aa_seq</code>.
     */
    public final TableField<YMainAaSequenceRecord, String> AA_SEQ = createField(DSL.name("aa_seq"), SQLDataType.CLOB.nullable(false), this, "");

    private YMainAaSequence(Name alias, Table<YMainAaSequenceRecord> aliased) {
        this(alias, aliased, null);
    }

    private YMainAaSequence(Name alias, Table<YMainAaSequenceRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>y_main_aa_sequence</code> table reference
     */
    public YMainAaSequence(String alias) {
        this(DSL.name(alias), Y_MAIN_AA_SEQUENCE);
    }

    /**
     * Create an aliased <code>y_main_aa_sequence</code> table reference
     */
    public YMainAaSequence(Name alias) {
        this(alias, Y_MAIN_AA_SEQUENCE);
    }

    /**
     * Create a <code>y_main_aa_sequence</code> table reference
     */
    public YMainAaSequence() {
        this(DSL.name("y_main_aa_sequence"), null);
    }

    public <O extends Record> YMainAaSequence(Table<O> child, ForeignKey<O, YMainAaSequenceRecord> key) {
        super(child, key, Y_MAIN_AA_SEQUENCE);
    }

    @Override
    public Schema getSchema() {
        return DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    public UniqueKey<YMainAaSequenceRecord> getPrimaryKey() {
        return Keys.Y_MAIN_AA_SEQUENCE_STAGING_PKEY;
    }

    @Override
    public List<UniqueKey<YMainAaSequenceRecord>> getKeys() {
        return Arrays.<UniqueKey<YMainAaSequenceRecord>>asList(Keys.Y_MAIN_AA_SEQUENCE_STAGING_PKEY);
    }

    @Override
    public YMainAaSequence as(String alias) {
        return new YMainAaSequence(DSL.name(alias), this);
    }

    @Override
    public YMainAaSequence as(Name alias) {
        return new YMainAaSequence(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public YMainAaSequence rename(String name) {
        return new YMainAaSequence(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public YMainAaSequence rename(Name name) {
        return new YMainAaSequence(name, null);
    }

    // -------------------------------------------------------------------------
    // Row3 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row3<Integer, String, String> fieldsRow() {
        return (Row3) super.fieldsRow();
    }
}
