/*
 * This file is generated by jOOQ.
 */
package org.jooq.lapis.tables;


import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row2;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;
import org.jooq.lapis.DefaultSchema;
import org.jooq.lapis.Keys;
import org.jooq.lapis.tables.records.YMainSequenceColumnarStagingRecord;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class YMainSequenceColumnarStaging extends TableImpl<YMainSequenceColumnarStagingRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>y_main_sequence_columnar_staging</code>
     */
    public static final YMainSequenceColumnarStaging Y_MAIN_SEQUENCE_COLUMNAR_STAGING = new YMainSequenceColumnarStaging();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<YMainSequenceColumnarStagingRecord> getRecordType() {
        return YMainSequenceColumnarStagingRecord.class;
    }

    /**
     * The column <code>y_main_sequence_columnar_staging.position</code>.
     */
    public final TableField<YMainSequenceColumnarStagingRecord, Integer> POSITION = createField(DSL.name("position"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>y_main_sequence_columnar_staging.data_compressed</code>.
     */
    public final TableField<YMainSequenceColumnarStagingRecord, byte[]> DATA_COMPRESSED = createField(DSL.name("data_compressed"), SQLDataType.BLOB.nullable(false), this, "");

    private YMainSequenceColumnarStaging(Name alias, Table<YMainSequenceColumnarStagingRecord> aliased) {
        this(alias, aliased, null);
    }

    private YMainSequenceColumnarStaging(Name alias, Table<YMainSequenceColumnarStagingRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>y_main_sequence_columnar_staging</code> table reference
     */
    public YMainSequenceColumnarStaging(String alias) {
        this(DSL.name(alias), Y_MAIN_SEQUENCE_COLUMNAR_STAGING);
    }

    /**
     * Create an aliased <code>y_main_sequence_columnar_staging</code> table reference
     */
    public YMainSequenceColumnarStaging(Name alias) {
        this(alias, Y_MAIN_SEQUENCE_COLUMNAR_STAGING);
    }

    /**
     * Create a <code>y_main_sequence_columnar_staging</code> table reference
     */
    public YMainSequenceColumnarStaging() {
        this(DSL.name("y_main_sequence_columnar_staging"), null);
    }

    public <O extends Record> YMainSequenceColumnarStaging(Table<O> child, ForeignKey<O, YMainSequenceColumnarStagingRecord> key) {
        super(child, key, Y_MAIN_SEQUENCE_COLUMNAR_STAGING);
    }

    @Override
    public Schema getSchema() {
        return DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    public UniqueKey<YMainSequenceColumnarStagingRecord> getPrimaryKey() {
        return Keys.Y_MAIN_SEQUENCE_COLUMNAR_PKEY;
    }

    @Override
    public List<UniqueKey<YMainSequenceColumnarStagingRecord>> getKeys() {
        return Arrays.<UniqueKey<YMainSequenceColumnarStagingRecord>>asList(Keys.Y_MAIN_SEQUENCE_COLUMNAR_PKEY);
    }

    @Override
    public YMainSequenceColumnarStaging as(String alias) {
        return new YMainSequenceColumnarStaging(DSL.name(alias), this);
    }

    @Override
    public YMainSequenceColumnarStaging as(Name alias) {
        return new YMainSequenceColumnarStaging(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public YMainSequenceColumnarStaging rename(String name) {
        return new YMainSequenceColumnarStaging(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public YMainSequenceColumnarStaging rename(Name name) {
        return new YMainSequenceColumnarStaging(name, null);
    }

    // -------------------------------------------------------------------------
    // Row2 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row2<Integer, byte[]> fieldsRow() {
        return (Row2) super.fieldsRow();
    }
}
