/*
 * This file is generated by jOOQ.
 */
package org.jooq.lapis.tables;


import java.time.LocalDate;
import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;
import org.jooq.lapis.DefaultSchema;
import org.jooq.lapis.Indexes;
import org.jooq.lapis.Keys;
import org.jooq.lapis.tables.records.YMainMetadataStagingRecord;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class YMainMetadataStaging extends TableImpl<YMainMetadataStagingRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>y_main_metadata_staging</code>
     */
    public static final YMainMetadataStaging Y_MAIN_METADATA_STAGING = new YMainMetadataStaging();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<YMainMetadataStagingRecord> getRecordType() {
        return YMainMetadataStagingRecord.class;
    }

    /**
     * The column <code>y_main_metadata_staging.id</code>.
     */
    public final TableField<YMainMetadataStagingRecord, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>y_main_metadata_staging.source</code>.
     */
    public final TableField<YMainMetadataStagingRecord, String> SOURCE = createField(DSL.name("source"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>y_main_metadata_staging.source_primary_key</code>.
     */
    public final TableField<YMainMetadataStagingRecord, String> SOURCE_PRIMARY_KEY = createField(DSL.name("source_primary_key"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>y_main_metadata_staging.genbank_accession</code>.
     */
    public final TableField<YMainMetadataStagingRecord, String> GENBANK_ACCESSION = createField(DSL.name("genbank_accession"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>y_main_metadata_staging.sra_accession</code>.
     */
    public final TableField<YMainMetadataStagingRecord, String> SRA_ACCESSION = createField(DSL.name("sra_accession"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>y_main_metadata_staging.gisaid_epi_isl</code>.
     */
    public final TableField<YMainMetadataStagingRecord, String> GISAID_EPI_ISL = createField(DSL.name("gisaid_epi_isl"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>y_main_metadata_staging.strain</code>.
     */
    public final TableField<YMainMetadataStagingRecord, String> STRAIN = createField(DSL.name("strain"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>y_main_metadata_staging.date</code>.
     */
    public final TableField<YMainMetadataStagingRecord, LocalDate> DATE = createField(DSL.name("date"), SQLDataType.LOCALDATE, this, "");

    /**
     * The column <code>y_main_metadata_staging.date_submitted</code>.
     */
    public final TableField<YMainMetadataStagingRecord, LocalDate> DATE_SUBMITTED = createField(DSL.name("date_submitted"), SQLDataType.LOCALDATE, this, "");

    /**
     * The column <code>y_main_metadata_staging.region</code>.
     */
    public final TableField<YMainMetadataStagingRecord, String> REGION = createField(DSL.name("region"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>y_main_metadata_staging.country</code>.
     */
    public final TableField<YMainMetadataStagingRecord, String> COUNTRY = createField(DSL.name("country"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>y_main_metadata_staging.division</code>.
     */
    public final TableField<YMainMetadataStagingRecord, String> DIVISION = createField(DSL.name("division"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>y_main_metadata_staging.location</code>.
     */
    public final TableField<YMainMetadataStagingRecord, String> LOCATION = createField(DSL.name("location"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>y_main_metadata_staging.region_exposure</code>.
     */
    public final TableField<YMainMetadataStagingRecord, String> REGION_EXPOSURE = createField(DSL.name("region_exposure"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>y_main_metadata_staging.country_exposure</code>.
     */
    public final TableField<YMainMetadataStagingRecord, String> COUNTRY_EXPOSURE = createField(DSL.name("country_exposure"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>y_main_metadata_staging.division_exposure</code>.
     */
    public final TableField<YMainMetadataStagingRecord, String> DIVISION_EXPOSURE = createField(DSL.name("division_exposure"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>y_main_metadata_staging.host</code>.
     */
    public final TableField<YMainMetadataStagingRecord, String> HOST = createField(DSL.name("host"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>y_main_metadata_staging.age</code>.
     */
    public final TableField<YMainMetadataStagingRecord, Integer> AGE = createField(DSL.name("age"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>y_main_metadata_staging.sex</code>.
     */
    public final TableField<YMainMetadataStagingRecord, String> SEX = createField(DSL.name("sex"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>y_main_metadata_staging.hospitalized</code>.
     */
    public final TableField<YMainMetadataStagingRecord, Boolean> HOSPITALIZED = createField(DSL.name("hospitalized"), SQLDataType.BOOLEAN, this, "");

    /**
     * The column <code>y_main_metadata_staging.died</code>.
     */
    public final TableField<YMainMetadataStagingRecord, Boolean> DIED = createField(DSL.name("died"), SQLDataType.BOOLEAN, this, "");

    /**
     * The column <code>y_main_metadata_staging.fully_vaccinated</code>.
     */
    public final TableField<YMainMetadataStagingRecord, Boolean> FULLY_VACCINATED = createField(DSL.name("fully_vaccinated"), SQLDataType.BOOLEAN, this, "");

    /**
     * The column <code>y_main_metadata_staging.sampling_strategy</code>.
     */
    public final TableField<YMainMetadataStagingRecord, String> SAMPLING_STRATEGY = createField(DSL.name("sampling_strategy"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>y_main_metadata_staging.pango_lineage</code>.
     */
    public final TableField<YMainMetadataStagingRecord, String> PANGO_LINEAGE = createField(DSL.name("pango_lineage"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>y_main_metadata_staging.nextclade_pango_lineage</code>.
     */
    public final TableField<YMainMetadataStagingRecord, String> NEXTCLADE_PANGO_LINEAGE = createField(DSL.name("nextclade_pango_lineage"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>y_main_metadata_staging.nextstrain_clade</code>.
     */
    public final TableField<YMainMetadataStagingRecord, String> NEXTSTRAIN_CLADE = createField(DSL.name("nextstrain_clade"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>y_main_metadata_staging.gisaid_clade</code>.
     */
    public final TableField<YMainMetadataStagingRecord, String> GISAID_CLADE = createField(DSL.name("gisaid_clade"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>y_main_metadata_staging.originating_lab</code>.
     */
    public final TableField<YMainMetadataStagingRecord, String> ORIGINATING_LAB = createField(DSL.name("originating_lab"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>y_main_metadata_staging.submitting_lab</code>.
     */
    public final TableField<YMainMetadataStagingRecord, String> SUBMITTING_LAB = createField(DSL.name("submitting_lab"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>y_main_metadata_staging.authors</code>.
     */
    public final TableField<YMainMetadataStagingRecord, String> AUTHORS = createField(DSL.name("authors"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>y_main_metadata_staging.nextclade_qc_overall_score</code>.
     */
    public final TableField<YMainMetadataStagingRecord, Double> NEXTCLADE_QC_OVERALL_SCORE = createField(DSL.name("nextclade_qc_overall_score"), SQLDataType.DOUBLE, this, "");

    /**
     * The column <code>y_main_metadata_staging.nextclade_qc_missing_data_score</code>.
     */
    public final TableField<YMainMetadataStagingRecord, Double> NEXTCLADE_QC_MISSING_DATA_SCORE = createField(DSL.name("nextclade_qc_missing_data_score"), SQLDataType.DOUBLE, this, "");

    /**
     * The column <code>y_main_metadata_staging.nextclade_qc_mixed_sites_score</code>.
     */
    public final TableField<YMainMetadataStagingRecord, Double> NEXTCLADE_QC_MIXED_SITES_SCORE = createField(DSL.name("nextclade_qc_mixed_sites_score"), SQLDataType.DOUBLE, this, "");

    /**
     * The column <code>y_main_metadata_staging.nextclade_qc_private_mutations_score</code>.
     */
    public final TableField<YMainMetadataStagingRecord, Double> NEXTCLADE_QC_PRIVATE_MUTATIONS_SCORE = createField(DSL.name("nextclade_qc_private_mutations_score"), SQLDataType.DOUBLE, this, "");

    /**
     * The column <code>y_main_metadata_staging.nextclade_qc_snp_clusters_score</code>.
     */
    public final TableField<YMainMetadataStagingRecord, Double> NEXTCLADE_QC_SNP_CLUSTERS_SCORE = createField(DSL.name("nextclade_qc_snp_clusters_score"), SQLDataType.DOUBLE, this, "");

    /**
     * The column <code>y_main_metadata_staging.nextclade_qc_frame_shifts_score</code>.
     */
    public final TableField<YMainMetadataStagingRecord, Double> NEXTCLADE_QC_FRAME_SHIFTS_SCORE = createField(DSL.name("nextclade_qc_frame_shifts_score"), SQLDataType.DOUBLE, this, "");

    /**
     * The column <code>y_main_metadata_staging.nextclade_qc_stop_codons_score</code>.
     */
    public final TableField<YMainMetadataStagingRecord, Double> NEXTCLADE_QC_STOP_CODONS_SCORE = createField(DSL.name("nextclade_qc_stop_codons_score"), SQLDataType.DOUBLE, this, "");

    /**
     * The column <code>y_main_metadata_staging.year</code>.
     */
    public final TableField<YMainMetadataStagingRecord, Integer> YEAR = createField(DSL.name("year"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>y_main_metadata_staging.month</code>.
     */
    public final TableField<YMainMetadataStagingRecord, Integer> MONTH = createField(DSL.name("month"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>y_main_metadata_staging.day</code>.
     */
    public final TableField<YMainMetadataStagingRecord, Integer> DAY = createField(DSL.name("day"), SQLDataType.INTEGER, this, "");

    private YMainMetadataStaging(Name alias, Table<YMainMetadataStagingRecord> aliased) {
        this(alias, aliased, null);
    }

    private YMainMetadataStaging(Name alias, Table<YMainMetadataStagingRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>y_main_metadata_staging</code> table reference
     */
    public YMainMetadataStaging(String alias) {
        this(DSL.name(alias), Y_MAIN_METADATA_STAGING);
    }

    /**
     * Create an aliased <code>y_main_metadata_staging</code> table reference
     */
    public YMainMetadataStaging(Name alias) {
        this(alias, Y_MAIN_METADATA_STAGING);
    }

    /**
     * Create a <code>y_main_metadata_staging</code> table reference
     */
    public YMainMetadataStaging() {
        this(DSL.name("y_main_metadata_staging"), null);
    }

    public <O extends Record> YMainMetadataStaging(Table<O> child, ForeignKey<O, YMainMetadataStagingRecord> key) {
        super(child, key, Y_MAIN_METADATA_STAGING);
    }

    @Override
    public Schema getSchema() {
        return DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.Y_MAIN_METADATA_STAGING_AGE_IDX, Indexes.Y_MAIN_METADATA_STAGING_COUNTRY_EXPOSURE_IDX, Indexes.Y_MAIN_METADATA_STAGING_COUNTRY_IDX, Indexes.Y_MAIN_METADATA_STAGING_DATE_IDX, Indexes.Y_MAIN_METADATA_STAGING_DATE_SUBMITTED_IDX, Indexes.Y_MAIN_METADATA_STAGING_DIED_IDX, Indexes.Y_MAIN_METADATA_STAGING_DIVISION_EXPOSURE_IDX, Indexes.Y_MAIN_METADATA_STAGING_DIVISION_IDX, Indexes.Y_MAIN_METADATA_STAGING_FULLY_VACCINATED_IDX, Indexes.Y_MAIN_METADATA_STAGING_GENBANK_ACCESSION_IDX, Indexes.Y_MAIN_METADATA_STAGING_GISAID_CLADE_IDX, Indexes.Y_MAIN_METADATA_STAGING_GISAID_EPI_ISL_IDX, Indexes.Y_MAIN_METADATA_STAGING_HOSPITALIZED_IDX, Indexes.Y_MAIN_METADATA_STAGING_HOST_IDX, Indexes.Y_MAIN_METADATA_STAGING_NEXTCLADE_PANGO_LINEAGE_IDX, Indexes.Y_MAIN_METADATA_STAGING_NEXTSTRAIN_CLADE_IDX, Indexes.Y_MAIN_METADATA_STAGING_ORIGINATING_LAB_IDX, Indexes.Y_MAIN_METADATA_STAGING_PANGO_LINEAGE_IDX, Indexes.Y_MAIN_METADATA_STAGING_REGION_EXPOSURE_IDX, Indexes.Y_MAIN_METADATA_STAGING_REGION_IDX, Indexes.Y_MAIN_METADATA_STAGING_SAMPLING_STRATEGY_IDX, Indexes.Y_MAIN_METADATA_STAGING_SEX_IDX, Indexes.Y_MAIN_METADATA_STAGING_SRA_ACCESSION_IDX, Indexes.Y_MAIN_METADATA_STAGING_STRAIN_IDX, Indexes.Y_MAIN_METADATA_STAGING_SUBMITTING_LAB_IDX);
    }

    @Override
    public UniqueKey<YMainMetadataStagingRecord> getPrimaryKey() {
        return Keys.Y_MAIN_METADATA_STAGING_PKEY;
    }

    @Override
    public List<UniqueKey<YMainMetadataStagingRecord>> getKeys() {
        return Arrays.<UniqueKey<YMainMetadataStagingRecord>>asList(Keys.Y_MAIN_METADATA_STAGING_PKEY);
    }

    @Override
    public YMainMetadataStaging as(String alias) {
        return new YMainMetadataStaging(DSL.name(alias), this);
    }

    @Override
    public YMainMetadataStaging as(Name alias) {
        return new YMainMetadataStaging(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public YMainMetadataStaging rename(String name) {
        return new YMainMetadataStaging(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public YMainMetadataStaging rename(Name name) {
        return new YMainMetadataStaging(name, null);
    }
}
