/*
 * This file is generated by jOOQ.
 */
package org.jooq.lapis.tables;


import java.time.LocalDate;
import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;
import org.jooq.lapis.DefaultSchema;
import org.jooq.lapis.Keys;
import org.jooq.lapis.tables.records.YNextstrainMpoxRecord;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class YNextstrainMpox extends TableImpl<YNextstrainMpoxRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>y_nextstrain_mpox</code>
     */
    public static final YNextstrainMpox Y_NEXTSTRAIN_MPOX = new YNextstrainMpox();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<YNextstrainMpoxRecord> getRecordType() {
        return YNextstrainMpoxRecord.class;
    }

    /**
     * The column <code>y_nextstrain_mpox.metadata_hash</code>.
     */
    public final TableField<YNextstrainMpoxRecord, String> METADATA_HASH = createField(DSL.name("metadata_hash"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>y_nextstrain_mpox.seq_original_hash</code>.
     */
    public final TableField<YNextstrainMpoxRecord, String> SEQ_ORIGINAL_HASH = createField(DSL.name("seq_original_hash"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>y_nextstrain_mpox.seq_aligned_hash</code>.
     */
    public final TableField<YNextstrainMpoxRecord, String> SEQ_ALIGNED_HASH = createField(DSL.name("seq_aligned_hash"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>y_nextstrain_mpox.strain</code>.
     */
    public final TableField<YNextstrainMpoxRecord, String> STRAIN = createField(DSL.name("strain"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>y_nextstrain_mpox.sra_accession</code>.
     */
    public final TableField<YNextstrainMpoxRecord, String> SRA_ACCESSION = createField(DSL.name("sra_accession"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>y_nextstrain_mpox.date</code>.
     */
    public final TableField<YNextstrainMpoxRecord, LocalDate> DATE = createField(DSL.name("date"), SQLDataType.LOCALDATE, this, "");

    /**
     * The column <code>y_nextstrain_mpox.year</code>.
     */
    public final TableField<YNextstrainMpoxRecord, Integer> YEAR = createField(DSL.name("year"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>y_nextstrain_mpox.month</code>.
     */
    public final TableField<YNextstrainMpoxRecord, Integer> MONTH = createField(DSL.name("month"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>y_nextstrain_mpox.day</code>.
     */
    public final TableField<YNextstrainMpoxRecord, Integer> DAY = createField(DSL.name("day"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>y_nextstrain_mpox.date_original</code>.
     */
    public final TableField<YNextstrainMpoxRecord, String> DATE_ORIGINAL = createField(DSL.name("date_original"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>y_nextstrain_mpox.region</code>.
     */
    public final TableField<YNextstrainMpoxRecord, String> REGION = createField(DSL.name("region"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>y_nextstrain_mpox.country</code>.
     */
    public final TableField<YNextstrainMpoxRecord, String> COUNTRY = createField(DSL.name("country"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>y_nextstrain_mpox.division</code>.
     */
    public final TableField<YNextstrainMpoxRecord, String> DIVISION = createField(DSL.name("division"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>y_nextstrain_mpox.host</code>.
     */
    public final TableField<YNextstrainMpoxRecord, String> HOST = createField(DSL.name("host"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>y_nextstrain_mpox.clade</code>.
     */
    public final TableField<YNextstrainMpoxRecord, String> CLADE = createField(DSL.name("clade"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>y_nextstrain_mpox.seq_original_compressed</code>.
     */
    public final TableField<YNextstrainMpoxRecord, byte[]> SEQ_ORIGINAL_COMPRESSED = createField(DSL.name("seq_original_compressed"), SQLDataType.BLOB, this, "");

    /**
     * The column <code>y_nextstrain_mpox.seq_aligned_compressed</code>.
     */
    public final TableField<YNextstrainMpoxRecord, byte[]> SEQ_ALIGNED_COMPRESSED = createField(DSL.name("seq_aligned_compressed"), SQLDataType.BLOB, this, "");

    /**
     * The column <code>y_nextstrain_mpox.aa_seqs_compressed</code>.
     */
    public final TableField<YNextstrainMpoxRecord, byte[]> AA_SEQS_COMPRESSED = createField(DSL.name("aa_seqs_compressed"), SQLDataType.BLOB, this, "");

    /**
     * The column <code>y_nextstrain_mpox.aa_mutations</code>.
     */
    public final TableField<YNextstrainMpoxRecord, String> AA_MUTATIONS = createField(DSL.name("aa_mutations"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>y_nextstrain_mpox.aa_unknowns</code>.
     */
    public final TableField<YNextstrainMpoxRecord, String> AA_UNKNOWNS = createField(DSL.name("aa_unknowns"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>y_nextstrain_mpox.nuc_substitutions</code>.
     */
    public final TableField<YNextstrainMpoxRecord, String> NUC_SUBSTITUTIONS = createField(DSL.name("nuc_substitutions"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>y_nextstrain_mpox.nuc_deletions</code>.
     */
    public final TableField<YNextstrainMpoxRecord, String> NUC_DELETIONS = createField(DSL.name("nuc_deletions"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>y_nextstrain_mpox.nuc_insertions</code>.
     */
    public final TableField<YNextstrainMpoxRecord, String> NUC_INSERTIONS = createField(DSL.name("nuc_insertions"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>y_nextstrain_mpox.nuc_unknowns</code>.
     */
    public final TableField<YNextstrainMpoxRecord, String> NUC_UNKNOWNS = createField(DSL.name("nuc_unknowns"), SQLDataType.CLOB, this, "");

    private YNextstrainMpox(Name alias, Table<YNextstrainMpoxRecord> aliased) {
        this(alias, aliased, null);
    }

    private YNextstrainMpox(Name alias, Table<YNextstrainMpoxRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>y_nextstrain_mpox</code> table reference
     */
    public YNextstrainMpox(String alias) {
        this(DSL.name(alias), Y_NEXTSTRAIN_MPOX);
    }

    /**
     * Create an aliased <code>y_nextstrain_mpox</code> table reference
     */
    public YNextstrainMpox(Name alias) {
        this(alias, Y_NEXTSTRAIN_MPOX);
    }

    /**
     * Create a <code>y_nextstrain_mpox</code> table reference
     */
    public YNextstrainMpox() {
        this(DSL.name("y_nextstrain_mpox"), null);
    }

    public <O extends Record> YNextstrainMpox(Table<O> child, ForeignKey<O, YNextstrainMpoxRecord> key) {
        super(child, key, Y_NEXTSTRAIN_MPOX);
    }

    @Override
    public Schema getSchema() {
        return DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    public UniqueKey<YNextstrainMpoxRecord> getPrimaryKey() {
        return Keys.Y_NEXTSTRAIN_MPOX_PKEY;
    }

    @Override
    public List<UniqueKey<YNextstrainMpoxRecord>> getKeys() {
        return Arrays.<UniqueKey<YNextstrainMpoxRecord>>asList(Keys.Y_NEXTSTRAIN_MPOX_PKEY);
    }

    @Override
    public YNextstrainMpox as(String alias) {
        return new YNextstrainMpox(DSL.name(alias), this);
    }

    @Override
    public YNextstrainMpox as(Name alias) {
        return new YNextstrainMpox(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public YNextstrainMpox rename(String name) {
        return new YNextstrainMpox(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public YNextstrainMpox rename(Name name) {
        return new YNextstrainMpox(name, null);
    }
}
