/*
 * This file is generated by jOOQ.
 */
package org.jooq.lapis.tables;


import java.time.LocalDate;
import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;
import org.jooq.lapis.DefaultSchema;
import org.jooq.lapis.Keys;
import org.jooq.lapis.tables.records.YNextstrainMpoxRecord;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class YNextstrainMpox extends TableImpl<YNextstrainMpoxRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>y_nextstrain_mpox</code>
     */
    public static final YNextstrainMpox Y_NEXTSTRAIN_MPOX = new YNextstrainMpox();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<YNextstrainMpoxRecord> getRecordType() {
        return YNextstrainMpoxRecord.class;
    }

    /**
     * The column <code>y_nextstrain_mpox.metadata_hash</code>.
     */
    public final TableField<YNextstrainMpoxRecord, String> METADATA_HASH = createField(DSL.name("metadata_hash"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>y_nextstrain_mpox.seq_original_hash</code>.
     */
    public final TableField<YNextstrainMpoxRecord, String> SEQ_ORIGINAL_HASH = createField(DSL.name("seq_original_hash"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>y_nextstrain_mpox.seq_aligned_hash</code>.
     */
    public final TableField<YNextstrainMpoxRecord, String> SEQ_ALIGNED_HASH = createField(DSL.name("seq_aligned_hash"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>y_nextstrain_mpox.accession</code>.
     */
    public final TableField<YNextstrainMpoxRecord, String> ACCESSION = createField(DSL.name("accession"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>y_nextstrain_mpox.accession_rev</code>.
     */
    public final TableField<YNextstrainMpoxRecord, String> ACCESSION_REV = createField(DSL.name("accession_rev"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>y_nextstrain_mpox.strain</code>.
     */
    public final TableField<YNextstrainMpoxRecord, String> STRAIN = createField(DSL.name("strain"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>y_nextstrain_mpox.sra_accession</code>.
     */
    public final TableField<YNextstrainMpoxRecord, String> SRA_ACCESSION = createField(DSL.name("sra_accession"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>y_nextstrain_mpox.date</code>.
     */
    public final TableField<YNextstrainMpoxRecord, LocalDate> DATE = createField(DSL.name("date"), SQLDataType.LOCALDATE, this, "");

    /**
     * The column <code>y_nextstrain_mpox.year</code>.
     */
    public final TableField<YNextstrainMpoxRecord, Integer> YEAR = createField(DSL.name("year"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>y_nextstrain_mpox.month</code>.
     */
    public final TableField<YNextstrainMpoxRecord, Integer> MONTH = createField(DSL.name("month"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>y_nextstrain_mpox.day</code>.
     */
    public final TableField<YNextstrainMpoxRecord, Integer> DAY = createField(DSL.name("day"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>y_nextstrain_mpox.date_original</code>.
     */
    public final TableField<YNextstrainMpoxRecord, String> DATE_ORIGINAL = createField(DSL.name("date_original"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>y_nextstrain_mpox.date_submitted</code>.
     */
    public final TableField<YNextstrainMpoxRecord, LocalDate> DATE_SUBMITTED = createField(DSL.name("date_submitted"), SQLDataType.LOCALDATE, this, "");

    /**
     * The column <code>y_nextstrain_mpox.region</code>.
     */
    public final TableField<YNextstrainMpoxRecord, String> REGION = createField(DSL.name("region"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>y_nextstrain_mpox.country</code>.
     */
    public final TableField<YNextstrainMpoxRecord, String> COUNTRY = createField(DSL.name("country"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>y_nextstrain_mpox.division</code>.
     */
    public final TableField<YNextstrainMpoxRecord, String> DIVISION = createField(DSL.name("division"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>y_nextstrain_mpox.location</code>.
     */
    public final TableField<YNextstrainMpoxRecord, String> LOCATION = createField(DSL.name("location"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>y_nextstrain_mpox.clade</code>.
     */
    public final TableField<YNextstrainMpoxRecord, String> CLADE = createField(DSL.name("clade"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>y_nextstrain_mpox.lineage</code>.
     */
    public final TableField<YNextstrainMpoxRecord, String> LINEAGE = createField(DSL.name("lineage"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>y_nextstrain_mpox.host</code>.
     */
    public final TableField<YNextstrainMpoxRecord, String> HOST = createField(DSL.name("host"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>y_nextstrain_mpox.authors</code>.
     */
    public final TableField<YNextstrainMpoxRecord, String> AUTHORS = createField(DSL.name("authors"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>y_nextstrain_mpox.institution</code>.
     */
    public final TableField<YNextstrainMpoxRecord, String> INSTITUTION = createField(DSL.name("institution"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>y_nextstrain_mpox.seq_original_compressed</code>.
     */
    public final TableField<YNextstrainMpoxRecord, byte[]> SEQ_ORIGINAL_COMPRESSED = createField(DSL.name("seq_original_compressed"), SQLDataType.BLOB, this, "");

    /**
     * The column <code>y_nextstrain_mpox.seq_aligned_compressed</code>.
     */
    public final TableField<YNextstrainMpoxRecord, byte[]> SEQ_ALIGNED_COMPRESSED = createField(DSL.name("seq_aligned_compressed"), SQLDataType.BLOB, this, "");

    /**
     * The column <code>y_nextstrain_mpox.aa_seqs_compressed</code>.
     */
    public final TableField<YNextstrainMpoxRecord, byte[]> AA_SEQS_COMPRESSED = createField(DSL.name("aa_seqs_compressed"), SQLDataType.BLOB, this, "");

    /**
     * The column <code>y_nextstrain_mpox.aa_mutations</code>.
     */
    public final TableField<YNextstrainMpoxRecord, String> AA_MUTATIONS = createField(DSL.name("aa_mutations"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>y_nextstrain_mpox.aa_unknowns</code>.
     */
    public final TableField<YNextstrainMpoxRecord, String> AA_UNKNOWNS = createField(DSL.name("aa_unknowns"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>y_nextstrain_mpox.nuc_substitutions</code>.
     */
    public final TableField<YNextstrainMpoxRecord, String> NUC_SUBSTITUTIONS = createField(DSL.name("nuc_substitutions"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>y_nextstrain_mpox.nuc_deletions</code>.
     */
    public final TableField<YNextstrainMpoxRecord, String> NUC_DELETIONS = createField(DSL.name("nuc_deletions"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>y_nextstrain_mpox.nuc_insertions</code>.
     */
    public final TableField<YNextstrainMpoxRecord, String> NUC_INSERTIONS = createField(DSL.name("nuc_insertions"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>y_nextstrain_mpox.nuc_unknowns</code>.
     */
    public final TableField<YNextstrainMpoxRecord, String> NUC_UNKNOWNS = createField(DSL.name("nuc_unknowns"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>y_nextstrain_mpox.nextclade_total_substitutions</code>.
     */
    public final TableField<YNextstrainMpoxRecord, Integer> NEXTCLADE_TOTAL_SUBSTITUTIONS = createField(DSL.name("nextclade_total_substitutions"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>y_nextstrain_mpox.nextclade_total_deletions</code>.
     */
    public final TableField<YNextstrainMpoxRecord, Integer> NEXTCLADE_TOTAL_DELETIONS = createField(DSL.name("nextclade_total_deletions"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>y_nextstrain_mpox.nextclade_total_insertions</code>.
     */
    public final TableField<YNextstrainMpoxRecord, Integer> NEXTCLADE_TOTAL_INSERTIONS = createField(DSL.name("nextclade_total_insertions"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>y_nextstrain_mpox.nextclade_total_frame_shifts</code>.
     */
    public final TableField<YNextstrainMpoxRecord, Integer> NEXTCLADE_TOTAL_FRAME_SHIFTS = createField(DSL.name("nextclade_total_frame_shifts"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>y_nextstrain_mpox.nextclade_total_aminoacid_substitutions</code>.
     */
    public final TableField<YNextstrainMpoxRecord, Integer> NEXTCLADE_TOTAL_AMINOACID_SUBSTITUTIONS = createField(DSL.name("nextclade_total_aminoacid_substitutions"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>y_nextstrain_mpox.nextclade_total_aminoacid_deletions</code>.
     */
    public final TableField<YNextstrainMpoxRecord, Integer> NEXTCLADE_TOTAL_AMINOACID_DELETIONS = createField(DSL.name("nextclade_total_aminoacid_deletions"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>y_nextstrain_mpox.nextclade_total_aminoacid_insertions</code>.
     */
    public final TableField<YNextstrainMpoxRecord, Integer> NEXTCLADE_TOTAL_AMINOACID_INSERTIONS = createField(DSL.name("nextclade_total_aminoacid_insertions"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>y_nextstrain_mpox.nextclade_total_missing</code>.
     */
    public final TableField<YNextstrainMpoxRecord, Integer> NEXTCLADE_TOTAL_MISSING = createField(DSL.name("nextclade_total_missing"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>y_nextstrain_mpox.nextclade_total_non_acgtns</code>.
     */
    public final TableField<YNextstrainMpoxRecord, Integer> NEXTCLADE_TOTAL_NON_ACGTNS = createField(DSL.name("nextclade_total_non_acgtns"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>y_nextstrain_mpox.nextclade_total_pcr_primer_changes</code>.
     */
    public final TableField<YNextstrainMpoxRecord, Integer> NEXTCLADE_TOTAL_PCR_PRIMER_CHANGES = createField(DSL.name("nextclade_total_pcr_primer_changes"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>y_nextstrain_mpox.nextclade_pcr_primer_changes</code>.
     */
    public final TableField<YNextstrainMpoxRecord, String> NEXTCLADE_PCR_PRIMER_CHANGES = createField(DSL.name("nextclade_pcr_primer_changes"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>y_nextstrain_mpox.nextclade_alignment_score</code>.
     */
    public final TableField<YNextstrainMpoxRecord, Double> NEXTCLADE_ALIGNMENT_SCORE = createField(DSL.name("nextclade_alignment_score"), SQLDataType.DOUBLE, this, "");

    /**
     * The column <code>y_nextstrain_mpox.nextclade_alignment_start</code>.
     */
    public final TableField<YNextstrainMpoxRecord, Integer> NEXTCLADE_ALIGNMENT_START = createField(DSL.name("nextclade_alignment_start"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>y_nextstrain_mpox.nextclade_alignment_end</code>.
     */
    public final TableField<YNextstrainMpoxRecord, Integer> NEXTCLADE_ALIGNMENT_END = createField(DSL.name("nextclade_alignment_end"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>y_nextstrain_mpox.nextclade_qc_overall_score</code>.
     */
    public final TableField<YNextstrainMpoxRecord, Double> NEXTCLADE_QC_OVERALL_SCORE = createField(DSL.name("nextclade_qc_overall_score"), SQLDataType.DOUBLE, this, "");

    /**
     * The column <code>y_nextstrain_mpox.nextclade_qc_overall_status</code>.
     */
    public final TableField<YNextstrainMpoxRecord, String> NEXTCLADE_QC_OVERALL_STATUS = createField(DSL.name("nextclade_qc_overall_status"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>y_nextstrain_mpox.nextclade_qc_missing_data_missing_data_threshold</code>.
     */
    public final TableField<YNextstrainMpoxRecord, Double> NEXTCLADE_QC_MISSING_DATA_MISSING_DATA_THRESHOLD = createField(DSL.name("nextclade_qc_missing_data_missing_data_threshold"), SQLDataType.DOUBLE, this, "");

    /**
     * The column <code>y_nextstrain_mpox.nextclade_qc_missing_data_score</code>.
     */
    public final TableField<YNextstrainMpoxRecord, Double> NEXTCLADE_QC_MISSING_DATA_SCORE = createField(DSL.name("nextclade_qc_missing_data_score"), SQLDataType.DOUBLE, this, "");

    /**
     * The column <code>y_nextstrain_mpox.nextclade_qc_missing_data_status</code>.
     */
    public final TableField<YNextstrainMpoxRecord, String> NEXTCLADE_QC_MISSING_DATA_STATUS = createField(DSL.name("nextclade_qc_missing_data_status"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>y_nextstrain_mpox.nextclade_qc_missing_data_total_missing</code>.
     */
    public final TableField<YNextstrainMpoxRecord, Integer> NEXTCLADE_QC_MISSING_DATA_TOTAL_MISSING = createField(DSL.name("nextclade_qc_missing_data_total_missing"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>y_nextstrain_mpox.nextclade_qc_mixed_sites_mixed_sites_threshold</code>.
     */
    public final TableField<YNextstrainMpoxRecord, Double> NEXTCLADE_QC_MIXED_SITES_MIXED_SITES_THRESHOLD = createField(DSL.name("nextclade_qc_mixed_sites_mixed_sites_threshold"), SQLDataType.DOUBLE, this, "");

    /**
     * The column <code>y_nextstrain_mpox.nextclade_qc_mixed_sites_score</code>.
     */
    public final TableField<YNextstrainMpoxRecord, Double> NEXTCLADE_QC_MIXED_SITES_SCORE = createField(DSL.name("nextclade_qc_mixed_sites_score"), SQLDataType.DOUBLE, this, "");

    /**
     * The column <code>y_nextstrain_mpox.nextclade_qc_mixed_sites_status</code>.
     */
    public final TableField<YNextstrainMpoxRecord, String> NEXTCLADE_QC_MIXED_SITES_STATUS = createField(DSL.name("nextclade_qc_mixed_sites_status"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>y_nextstrain_mpox.nextclade_qc_mixed_sites_total_mixed_sites</code>.
     */
    public final TableField<YNextstrainMpoxRecord, Integer> NEXTCLADE_QC_MIXED_SITES_TOTAL_MIXED_SITES = createField(DSL.name("nextclade_qc_mixed_sites_total_mixed_sites"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>y_nextstrain_mpox.nextclade_qc_private_mutations_cutoff</code>.
     */
    public final TableField<YNextstrainMpoxRecord, Double> NEXTCLADE_QC_PRIVATE_MUTATIONS_CUTOFF = createField(DSL.name("nextclade_qc_private_mutations_cutoff"), SQLDataType.DOUBLE, this, "");

    /**
     * The column <code>y_nextstrain_mpox.nextclade_qc_private_mutations_excess</code>.
     */
    public final TableField<YNextstrainMpoxRecord, Double> NEXTCLADE_QC_PRIVATE_MUTATIONS_EXCESS = createField(DSL.name("nextclade_qc_private_mutations_excess"), SQLDataType.DOUBLE, this, "");

    /**
     * The column <code>y_nextstrain_mpox.nextclade_qc_private_mutations_score</code>.
     */
    public final TableField<YNextstrainMpoxRecord, Double> NEXTCLADE_QC_PRIVATE_MUTATIONS_SCORE = createField(DSL.name("nextclade_qc_private_mutations_score"), SQLDataType.DOUBLE, this, "");

    /**
     * The column <code>y_nextstrain_mpox.nextclade_qc_private_mutations_status</code>.
     */
    public final TableField<YNextstrainMpoxRecord, String> NEXTCLADE_QC_PRIVATE_MUTATIONS_STATUS = createField(DSL.name("nextclade_qc_private_mutations_status"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>y_nextstrain_mpox.nextclade_qc_private_mutations_total</code>.
     */
    public final TableField<YNextstrainMpoxRecord, Integer> NEXTCLADE_QC_PRIVATE_MUTATIONS_TOTAL = createField(DSL.name("nextclade_qc_private_mutations_total"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>y_nextstrain_mpox.nextclade_qc_snp_clusters_clustered_snps</code>.
     */
    public final TableField<YNextstrainMpoxRecord, String> NEXTCLADE_QC_SNP_CLUSTERS_CLUSTERED_SNPS = createField(DSL.name("nextclade_qc_snp_clusters_clustered_snps"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>y_nextstrain_mpox.nextclade_qc_snp_clusters_score</code>.
     */
    public final TableField<YNextstrainMpoxRecord, Double> NEXTCLADE_QC_SNP_CLUSTERS_SCORE = createField(DSL.name("nextclade_qc_snp_clusters_score"), SQLDataType.DOUBLE, this, "");

    /**
     * The column <code>y_nextstrain_mpox.nextclade_qc_snp_clusters_status</code>.
     */
    public final TableField<YNextstrainMpoxRecord, String> NEXTCLADE_QC_SNP_CLUSTERS_STATUS = createField(DSL.name("nextclade_qc_snp_clusters_status"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>y_nextstrain_mpox.nextclade_qc_snp_clusters_total_snps</code>.
     */
    public final TableField<YNextstrainMpoxRecord, Integer> NEXTCLADE_QC_SNP_CLUSTERS_TOTAL_SNPS = createField(DSL.name("nextclade_qc_snp_clusters_total_snps"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>y_nextstrain_mpox.nextclade_qc_frame_shifts_frame_shifts</code>.
     */
    public final TableField<YNextstrainMpoxRecord, String> NEXTCLADE_QC_FRAME_SHIFTS_FRAME_SHIFTS = createField(DSL.name("nextclade_qc_frame_shifts_frame_shifts"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>y_nextstrain_mpox.nextclade_qc_frame_shifts_total_frame_shifts</code>.
     */
    public final TableField<YNextstrainMpoxRecord, Integer> NEXTCLADE_QC_FRAME_SHIFTS_TOTAL_FRAME_SHIFTS = createField(DSL.name("nextclade_qc_frame_shifts_total_frame_shifts"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>y_nextstrain_mpox.nextclade_qc_frame_shifts_frame_shifts_ignored</code>.
     */
    public final TableField<YNextstrainMpoxRecord, String> NEXTCLADE_QC_FRAME_SHIFTS_FRAME_SHIFTS_IGNORED = createField(DSL.name("nextclade_qc_frame_shifts_frame_shifts_ignored"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>y_nextstrain_mpox.nextclade_qc_frame_shifts_total_frame_shifts_ignored</code>.
     */
    public final TableField<YNextstrainMpoxRecord, Integer> NEXTCLADE_QC_FRAME_SHIFTS_TOTAL_FRAME_SHIFTS_IGNORED = createField(DSL.name("nextclade_qc_frame_shifts_total_frame_shifts_ignored"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>y_nextstrain_mpox.nextclade_qc_frame_shifts_score</code>.
     */
    public final TableField<YNextstrainMpoxRecord, Double> NEXTCLADE_QC_FRAME_SHIFTS_SCORE = createField(DSL.name("nextclade_qc_frame_shifts_score"), SQLDataType.DOUBLE, this, "");

    /**
     * The column <code>y_nextstrain_mpox.nextclade_qc_frame_shifts_status</code>.
     */
    public final TableField<YNextstrainMpoxRecord, String> NEXTCLADE_QC_FRAME_SHIFTS_STATUS = createField(DSL.name("nextclade_qc_frame_shifts_status"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>y_nextstrain_mpox.nextclade_qc_stop_codons_stop_codons</code>.
     */
    public final TableField<YNextstrainMpoxRecord, String> NEXTCLADE_QC_STOP_CODONS_STOP_CODONS = createField(DSL.name("nextclade_qc_stop_codons_stop_codons"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>y_nextstrain_mpox.nextclade_qc_stop_codons_total_stop_codons</code>.
     */
    public final TableField<YNextstrainMpoxRecord, Integer> NEXTCLADE_QC_STOP_CODONS_TOTAL_STOP_CODONS = createField(DSL.name("nextclade_qc_stop_codons_total_stop_codons"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>y_nextstrain_mpox.nextclade_qc_stop_codons_score</code>.
     */
    public final TableField<YNextstrainMpoxRecord, Double> NEXTCLADE_QC_STOP_CODONS_SCORE = createField(DSL.name("nextclade_qc_stop_codons_score"), SQLDataType.DOUBLE, this, "");

    /**
     * The column <code>y_nextstrain_mpox.nextclade_qc_stop_codons_status</code>.
     */
    public final TableField<YNextstrainMpoxRecord, String> NEXTCLADE_QC_STOP_CODONS_STATUS = createField(DSL.name("nextclade_qc_stop_codons_status"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>y_nextstrain_mpox.nextclade_errors</code>.
     */
    public final TableField<YNextstrainMpoxRecord, String> NEXTCLADE_ERRORS = createField(DSL.name("nextclade_errors"), SQLDataType.CLOB, this, "");

    private YNextstrainMpox(Name alias, Table<YNextstrainMpoxRecord> aliased) {
        this(alias, aliased, null);
    }

    private YNextstrainMpox(Name alias, Table<YNextstrainMpoxRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>y_nextstrain_mpox</code> table reference
     */
    public YNextstrainMpox(String alias) {
        this(DSL.name(alias), Y_NEXTSTRAIN_MPOX);
    }

    /**
     * Create an aliased <code>y_nextstrain_mpox</code> table reference
     */
    public YNextstrainMpox(Name alias) {
        this(alias, Y_NEXTSTRAIN_MPOX);
    }

    /**
     * Create a <code>y_nextstrain_mpox</code> table reference
     */
    public YNextstrainMpox() {
        this(DSL.name("y_nextstrain_mpox"), null);
    }

    public <O extends Record> YNextstrainMpox(Table<O> child, ForeignKey<O, YNextstrainMpoxRecord> key) {
        super(child, key, Y_NEXTSTRAIN_MPOX);
    }

    @Override
    public Schema getSchema() {
        return DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    public UniqueKey<YNextstrainMpoxRecord> getPrimaryKey() {
        return Keys.Y_NEXTSTRAIN_MPOX_PKEY;
    }

    @Override
    public List<UniqueKey<YNextstrainMpoxRecord>> getKeys() {
        return Arrays.<UniqueKey<YNextstrainMpoxRecord>>asList(Keys.Y_NEXTSTRAIN_MPOX_PKEY);
    }

    @Override
    public YNextstrainMpox as(String alias) {
        return new YNextstrainMpox(DSL.name(alias), this);
    }

    @Override
    public YNextstrainMpox as(Name alias) {
        return new YNextstrainMpox(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public YNextstrainMpox rename(String name) {
        return new YNextstrainMpox(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public YNextstrainMpox rename(Name name) {
        return new YNextstrainMpox(name, null);
    }
}
